$PROBLEM est-its-foce - ITS followed by FOCE-I (METHOD=COND INTER) with MATRIX=R covariance
$INPUT ID TIME AMT RATE EVID CMT SS II ADDL DV MDV ROWID
$DATA data.csv IGNORE=@
$SUBROUTINES ADVAN2 TRANS2
$PK
  CL = THETA(1)*EXP(ETA(1))
  V  = THETA(2)*EXP(ETA(2))
  KA = THETA(3)
  S2 = V
$ERROR
  IPRED = F
  W = THETA(4)*IPRED
  IF (W .EQ. 0) W = 1
  IWRES = (DV - IPRED)/W
  Y = IPRED + W*EPS(1)
$THETA (0, 3) (0, 30) (0, 1.2) (0, 0.1)
$OMEGA 0.09 0.04
$SIGMA 1 FIX
$EST METHOD=ITS INTER NITER=50 PRINT=10 NOABORT
$EST METHOD=COND INTER MAXEVAL=9999 PRINT=5 NOABORT
$COV MATRIX=R UNCONDITIONAL
$TABLE ID TIME EVID ROWID IPRED IWRES ONEHEADER NOPRINT FILE=run.tab
$TABLE ID ETAS(1:LAST) FIRSTONLY ONEHEADER NOPRINT NOAPPEND FILE=run.eta

