$PROBLEM ADVAN5 three-compartment linear system (matExp translation test)
$INPUT ID TIME DV AMT EVID CMT
$DATA advan5.csv IGNORE=@
$SUBROUTINE ADVAN5
$MODEL COMP=(DEPOT,DEFDOS) COMP=(CENTRAL,DEFOBS) COMP=(PERIPH)
$PK
K12 = THETA(1)*EXP(ETA(1))
K23 = THETA(2)
K32 = THETA(3)
K20 = THETA(4)
S2 = 1
$ERROR
IPRED = A(2)
Y = IPRED*(1+ERR(1))
$THETA 1    ; TVK12
$THETA 0.5  ; TVK23
$THETA 0.2  ; TVK32
$THETA 0.3  ; TVK20
$OMEGA 0.1  ; IIV K12
$SIGMA 0.01
$EST METHOD=1 MAXEVAL=0
