if (identical(Sys.getenv("NOT_CRAN"), "true")) {

  .files <-c("PsN/courses/upss/lasso/run2.lst",
             "PsN/courses/upss/lasso/run1.lst",
             "PsN/test_files/mox_sir.lst", # has phi
             "PsN/test_files/pheno_real.lst",
             "PsN/test_files/mox1.lst",
             "PsN/test_files/phenofull.lst",
             "PsN/test_files/cdd/some_cov_fail/cdd_6.lst",
             "PsN/test_files/cdd/some_cov_fail/cdd_2.lst",
             "PsN/test_files/cdd/some_cov_fail/cdd_7.lst",
             "PsN/test_files/cdd/some_cov_fail/cdd_9.lst",
             "PsN/test_files/cdd/some_cov_fail/cdd_5.lst",
             "PsN/test_files/cdd/some_cov_fail/cdd_1.lst",
             "PsN/test_files/cdd/some_cov_fail/cdd_3.lst",
             "PsN/test_files/cdd/some_cov_fail/cdd_10.lst",
             "PsN/test_files/cdd/some_cov_fail/cdd_4.lst",
             "PsN/test_files/cdd/some_cov_fail/run87.lst",
             "PsN/test_files/cdd/some_cov_fail/cdd_8.lst",
             "PsN/test_files/pheno_test.lst",
             "PsN/test_files/scmplus/pheno_localmin.lst",
             "PsN/test_files/scmplus/run1.lst",
             "PsN/test_files/scmplus/pheno.lst",
             "PsN/test_files/scmplus/pheno_with_cov.lst",
             "PsN/test_files/scmplus/monitor/maxeval_exceeded.lst",
             "PsN/test_files/scmplus/monitor/modelfit_running/NM_run3/psn.lst",
             "PsN/test_files/scmplus/monitor/active_scm_dir1/modelfit_dir1/NM_run4/psn.lst",
             "PsN/test_files/scmplus/monitor/active_scm_dir1/modelfit_dir1/NM_run2/psn.lst",
             "PsN/test_files/scmplus/monitor/active_scm_dir1/modelfit_dir1/NM_run1/psn.lst",
             "PsN/test_files/scmplus/monitor/active_scm_dir1/modelfit_dir1/NM_run3/psn.lst",
             "PsN/test_files/scmplus/monitor/active_scm_dir1/modelfit_dir1/NM_run5/psn.lst",
             "PsN/test_files/scmplus/monitor/active_scm_dir1/m1/VCVD12.lst",
             "PsN/test_files/scmplus/monitor/active_scm_dir1/m1/CLCV12.lst",
             "PsN/test_files/scmplus/monitor/active_scm_dir1/m1/CLWGT2.lst",
             "PsN/test_files/scmplus/monitor/active_scm_dir1/m1/VCV22.lst",
             "PsN/test_files/mox_sir_block2.lst",
             "PsN/test_files/sir/localmin.lst",
             "PsN/test_files/sir/moxo.lst",
             "PsN/test_files/sir/run1_noblock.lst",
             "PsN/test_files/sir/for_cv_matrix.lst",
             "PsN/test_files/modelfit/diagnose_lst_errors/psn.lst",
             "PsN/test_files/scm/pheno_ignore.lst",
             "PsN/test_files/scm/pheno_nohead.lst",
             "PsN/test_files/scm/pheno_with_tv.lst",
             "PsN/test_files/scm/pheno_with_cov_foce_prop.lst",
             "PsN/test_files/scm/filter_data.lst",
             "PsN/test_files/scm/pheno_with_cov.lst",
             "PsN/test_files/scm/pheno_logit.lst",
             "PsN/test_files/pheno_cond.lst",
             "PsN/test_files/output/msfi/sim_noest_Vvi_20.lst",
             "PsN/test_files/output/msfi/tab_Vvi_20.lst",
             "PsN/test_files/output/msfi/cov_V7.lst",
             "PsN/test_files/output/msfi/cov_V7_30_beta.lst",
             "PsN/test_files/output/special_mod/nwpri.lst",
             "PsN/test_files/output/special_mod/large_standard_errors.lst",
             "PsN/test_files/output/special_mod/allfix.lst",
             "PsN/test_files/output/special_mod/maxeval_exceeded.lst",
             "PsN/test_files/output/special_mod/sparse_format_cov_matrix.lst",
             "PsN/test_files/output/special_mod/high_correlations.lst",
             "PsN/test_files/output/special_mod/nonclassical_interrupted/interrupt_bayes.lst",
             "PsN/test_files/output/special_mod/nonclassical_interrupted/interrupt_imp.lst",
             "PsN/test_files/output/special_mod/nonclassical_interrupted/interrupt_saem.lst",
             "PsN/test_files/output/special_mod/nonclassical_interrupted/interrupt_its.lst",
             "PsN/test_files/output/special_mod/nonclassical_interrupted/interrupt_impmap.lst",
             "PsN/test_files/output/special_mod/license_missing.lst",
             "PsN/test_files/output/special_mod/license_expired.lst",
             "PsN/test_files/output/special_mod/tnpri.lst",
             "PsN/test_files/output/special_mod/near_bounds.lst",
             "PsN/test_files/output/special_mod/covcrash_noext.lst",
             "PsN/test_files/output/special_mod/license_dummy.lst",
             "PsN/test_files/output/special_mod/zeroruntime.lst",
             #          "PsN/test_files/output/special_mod/minimterm_cov_unconditional.lst",
             "PsN/test_files/output/special_mod/UseCase1.lst",
             "PsN/test_files/output/special_mod/warfarin_saem_noest.lst",
             "PsN/test_files/output/special_mod/theo_t_matrix.lst",
             #"PsN/test_files/output/special_mod/special_inverse.lst",
             "PsN/test_files/output/special_mod/covcrash.lst",
             "PsN/test_files/output/special_mod/s_matrix_singular.lst",
             "PsN/test_files/output/special_mod/data_missing.lst",
             "PsN/test_files/output/special_mod/postprocesstime.lst",
             "PsN/test_files/output/special_mod/allfix_estimation.lst",
             "PsN/test_files/output/nm6/pheno_nonp_nm6.lst",
             "PsN/test_files/output/onePROB/oneEST/withSIM/evaluation_nm730.lst",
             "PsN/test_files/output/onePROB/oneEST/withSIM/cov_nsub2_V7_30_beta.lst",
             "PsN/test_files/output/onePROB/oneEST/withSIM/cov_nsub2_Vvi_10.lst",
             "PsN/test_files/output/onePROB/oneEST/noSIM/hessian_error.lst",
             "PsN/test_files/output/onePROB/oneEST/noSIM/warfarin_noext.lst",
             "PsN/test_files/output/onePROB/oneEST/noSIM/phenocorr.lst",
             "PsN/test_files/output/onePROB/oneEST/noSIM/nm710_fail_negV.lst",
             "PsN/test_files/output/onePROB/oneEST/noSIM/sparse_matrix_with_msfi.lst",
             "PsN/test_files/output/onePROB/multEST/firstEstTerm.lst",
             "PsN/test_files/output/onePROB/noEST/withSIM/witheval_nm710.lst",
             "PsN/test_files/output/onePROB/noEST/withSIM/noeval_nm712.lst",
             "PsN/test_files/output/onePROB/noEST/withSIM/witheval_nm712.lst",
             "PsN/test_files/output/onePROB/noEST/withSIM/witheval_nm73.lst",
             "PsN/test_files/output/onePROB/noEST/withSIM/noeval_fail_nm73.lst",
             "PsN/test_files/output/onePROB/noEST/withSIM/noeval_nm72.lst",
             "PsN/test_files/output/onePROB/noEST/withSIM/witheval_nm72.lst",
             "PsN/test_files/output/onePROB/noEST/withSIM/noeval_nm710.lst",
             "PsN/test_files/output/onePROB/noEST/withSIM/noeval_nm73.lst",
             "PsN/test_files/output/onePROB/noEST/withSIM/witheval_fail_nm710.lst",
             "PsN/test_files/output/onePROB/noEST/withSIM/witheval_fail_nm73.lst",
             "PsN/test_files/output/onePROB/noEST/withSIM/witheval_fail_nm712.lst",
             "PsN/test_files/output/multPROB/oneEST/withSIM/p1_cov_p2_sim_noest_V7_10_g_reg.lst",
             "PsN/test_files/output/multPROB/oneEST/withSIM/p1_cov_p2_sim_noest_V7_20_g.lst",
             "PsN/test_files/output/multPROB/oneEST/noSIM/multprob_nm712.lst",
             "PsN/test_files/output/multPROB/oneEST/noSIM/multprob_nm720.lst",
             "PsN/test_files/output/multPROB/oneEST/noSIM/p1_p2_tab_noest_Vvi_20.lst",
             "PsN/test_files/output/multPROB/oneEST/noSIM/multprob_nm740beta.lst",
             "PsN/test_files/output/multPROB/oneEST/noSIM/multprob_nm710.lst",
             "PsN/test_files/output/multPROB/oneEST/noSIM/multprob_nm730.lst",
             "PsN/test_files/output/multPROB/oneEST/noSIM/multprob_nm712_noext.lst",
             "PsN/test_files/output/multPROB/multEST/withSIM/nonclassical_sim_eval_nm712.lst",
             "PsN/test_files/output/multPROB/multEST/withSIM/multprobmix_2_nm740alpha.lst",
             "PsN/test_files/output/multPROB/multEST/withSIM/nonclassical_sim_eval_nm710.lst",
             "PsN/test_files/output/multPROB/multEST/withSIM/multprobmix_2_nm712.lst",
             "PsN/test_files/output/multPROB/multEST/withSIM/multprobmix_nm720.lst",
             "PsN/test_files/output/multPROB/multEST/withSIM/max100_max100_V7_10_g_reg.lst",
             "PsN/test_files/output/multPROB/multEST/withSIM/multprobmix_3_nm730.lst",
             "PsN/test_files/output/multPROB/multEST/withSIM/multprobmix_2_nm720.lst",
             "PsN/test_files/output/multPROB/multEST/withSIM/multprobmix_2_nm710.lst",
             "PsN/test_files/output/multPROB/multEST/withSIM/nonclassical_sim_eval_nm720.lst",
             "PsN/test_files/output/multPROB/multEST/withSIM/multprobmix_nm712.lst",
             "PsN/test_files/output/multPROB/multEST/withSIM/multprobmix_nm740alpha.lst",
             "PsN/test_files/output/multPROB/multEST/withSIM/max100_max100_V7_30_beta.lst",
             "PsN/test_files/output/multPROB/multEST/withSIM/multprobmix_nm710.lst",
             "PsN/test_files/output/multPROB/multEST/withSIM/multprobmix_nm730.lst",
             "PsN/test_files/output/multPROB/multEST/withSIM/nonclassical_sim_eval_nm730.lst",
             "PsN/test_files/output/multPROB/multEST/noSIM/nonclassical_eval_nm710.lst",
             "PsN/test_files/output/multPROB/multEST/noSIM/p1_p2_tab_noest_V7_30_beta.lst",
             "PsN/test_files/output/multPROB/multEST/noSIM/p1_p2_cov_V7_20_g.lst",
             "PsN/test_files/output/multPROB/multEST/noSIM/p1_p2_tab_noest_V7.lst",
             "PsN/test_files/output/multPROB/multEST/noSIM/nonclassical_eval_nm712.lst",
             "PsN/test_files/output/multPROB/multEST/noSIM/nonclassical_eval_nm720.lst",
             "PsN/test_files/output/multPROB/multEST/noSIM/nonclassical_eval_nm730.lst",
             "PsN/test_files/output/multPROB/multEST/noSIM/p1_p2_cov_V7.lst",
             "PsN/test_files/output/multPROB/multEST/noSIM/nonclassicalest_nm730.lst",
             "PsN/test_files/output/multPROB/multEST/noSIM/p1_p2_tab_noest_V7_20_g.lst",
             "PsN/test_files/output/multPROB/multEST/noSIM/nonclassicalest_nm720.lst",
             "PsN/test_files/output/multPROB/multEST/noSIM/nonclassicalest_nm710.lst",
             "PsN/test_files/output/multPROB/multEST/noSIM/p1_p2_cov_V7_12_g_reg.lst",
             "PsN/test_files/output/multPROB/multEST/noSIM/p1_p2_cov_V7_30_beta.lst",
             "PsN/test_files/output/multPROB/multEST/noSIM/p1_p2_tab_noest_V7_10_g_reg.lst",
             "PsN/test_files/output/multPROB/multEST/noSIM/p1_p2_tab_noest_V7_12_g_reg.lst",
             "PsN/test_files/output/multPROB/multEST/noSIM/p1_p2_cov_V7_10_g_reg.lst",
             "PsN/test_files/output/multPROB/multEST/noSIM/nonclassicalest_nm712.lst",
             "PsN/test_files/output/multPROB/noEST/withSIM/sim_noest_V7_30.lst",
             "PsN/test_files/output/nm74/only_nonparametric.lst",
             "PsN/test_files/output/nm74/final_forward.lst",
             "PsN/test_files/output/nm74/prior.lst",
             "PsN/test_files/output/nm74/final_forward2.lst",
             "PsN/test_files/output/nm73/superid2_6_V7_30_beta.lst",
             "PsN/test_files/output/nm73/theo_withcov.lst",
             "PsN/test_files/output/nm73/mox_nocov_nonp.lst",
             "PsN/test_files/output/nm73/anneal2_V7_30_beta.lst",
             "PsN/test_files/output/nm73/mox_fail_nonp.lst",
             "PsN/test_files/output/nm73/UseCase7.lst",
             "PsN/test_files/output/nm73/pheno_nonp.lst",
             "PsN/test_files/output/nm73/example6b_V7_30_beta.lst",
             "PsN/test_files/output/nm73/theo_nonp.lst",
             "PsN/test_files/output/nm73/theo.lst",
             "PsN/test_files/phenoMAXEV0.lst",
             "PsN/test_files/matrixreal.lst",
             "PsN/test_files/mox_frem.lst",
             "PsN/test_files/pheno5.lst",
             "PsN/test_files/pheno.lst",
             "PsN/test_files/frem/compact.lst",
             "PsN/test_files/frem/hamren_4.lst",
             "PsN/test_files/frem/mox_imp_4.lst",
             "PsN/test_files/frem/model_4.lst",
             "PsN/test_files/frem/model_2.lst",
             "PsN/test_files/frem/model_1.lst",
             "PsN/test_files/SO/parser_psn/vpcrun/rundir/vpc_original.lst",
             "PsN/test_files/SO/parser_psn/vpcrun/rundir/m1/vpc_simulation.1.lst",
             "PsN/test_files/SO/parser_psn/vpcrun/pheno5.lst",
             "PsN/test_files/SO/parser_psn/sserun/rundir/m1/mc-2.lst",
             "PsN/test_files/SO/parser_psn/sserun/rundir/m1/mc-3.lst",
             "PsN/test_files/SO/parser_psn/sserun/rundir/m1/mc-1.lst",
             "PsN/test_files/SO/parser_psn/sserun/pheno5.lst",
             "PsN/test_files/SO/parser_psn/bootrun/rundir/m1/bs_pr1_3.lst",
             "PsN/test_files/SO/parser_psn/bootrun/rundir/m1/bs_pr1_2.lst",
             "PsN/test_files/SO/parser_psn/bootrun/rundir/m1/bs_pr1_1.lst",
             "PsN/test_files/SO/parser_psn/bootrun/pheno5.lst",
             "PsN/test_files/SO/parser_psn/executerun/pheno5.lst",
             "PsN/test_files/SO/DelBene/DelBene_2009_oncology_in_vitro_EPS_in_OBS.lst",
             "PsN/test_files/SO/Simeoni/Simeoni_2004_oncology_TGI_ETA.lst",
             "PsN/test_files/SO/Nock/Nock_2013_Carboplatin_PK_MONOLIX.lst",
             "PsN/test_files/SO/pheno.lst",
             "PsN/test_files/SO/BOV/run3.lst",
             "PsN/test_files/SO/pheno_sdcorr.lst",
             "PsN/test_files/mox_no_bov.lst",
             "PsN/test_files/postfrem/frem_sir/final_models/model_4.lst",
             "PsN/test_files/postfrem/frem_covstep/final_models/model_4.lst",
             "PsN/test_files/postfrem/frem_covstep_removed/final_models/model_4.lst",
             "PsN/test_files/run45.lst",
             "PsN/test_files/output/onePROB/oneEST/noSIM/warfarin_ddmore.lst",
             "PsN/test_files/output/special_mod/rounding_errors.lst",
             "PsN/test_files/output/special_mod/two_digit_cov_index.lst",
             "PsN/test_files/output/nm6/nm61_1.lst")

  .fileError <- c("PsN/test_files/output/special_mod/missingmodel.lst",
                  "PsN/test_files/output/special_mod/empty.lst",
                  "PsN/test_files/output/special_mod/empty_lines.lst",
                  #bad advan
                  # bad lincmt
                  "PsN/test_files/output/special_mod/objv_infinity.lst",
                  "PsN/test_files/output/special_mod/interrupted_at_eigen.lst",
                  "PsN/test_files/output/nm74/sparse_matrix_bug.lst",
                  "PsN/test_files/output/onePROB/oneEST/noSIM/large_s_matrix_cov_fail.lst",
                  "PsN/test_files/output/special_mod/two_prob_second_fail.lst")

  withr::with_tempdir({

    unzip(system.file("PsN.zip", package="nonmem2rx"))

    withr::with_options(list(nonmem2rx.save=FALSE, nonmem2rx.load=FALSE, nonmem2rx.overwrite=FALSE,
                             nonmem2rx.extended=FALSE),
    {

      lapply(.files,
             function(file) {
               test_that(file, {
                 expect_error(suppressMessages(suppressWarnings(nonmem2rx(file, strictLst=TRUE, save=FALSE))), NA)
               })
             })

      lapply(.fileError,
             function(file) {
               test_that(paste0("error for ", file), {
                 expect_error(suppressMessages(suppressWarnings(nonmem2rx(file, strictLst=TRUE, save=FALSE))))
               })
             })

      lapply(.fileError,
             function(file) {
               test_that("list for error file", {
                 expect_error(suppressMessages(suppressWarnings(nmlst(file, strictLst=TRUE))), NA)
               })
             })

    })

    withr::with_options(list(nonmem2rx.save=FALSE, nonmem2rx.load=FALSE, nonmem2rx.overwrite=FALSE,
                             nonmem2rx.extended=TRUE),
    {
      lapply(.files,
             function(file) {
               test_that(paste0(file, " extended"), {
                 expect_error(suppressMessages(suppressWarnings(nonmem2rx(file, strictLst=TRUE))), NA)
               })
             })
    })
  })
}
