test_that("test error parsing", {
  
  expect_true(.isParamWeps(quote(y<-ipred+w*eps1)))
  expect_false(.isParamWeps(quote(y<-ipred+w/eps1)))
  expect_true(.isParamWeps(quote(y<-ipred+eps1*w)))
  expect_true(.isParamWeps(quote(y<-f+w*eps1)))
  expect_true(.isParamWeps(quote(y<-f+eps1*w)))
  expect_true(.isParamWeps(quote(y<-w*eps1+ipred)))
  expect_true(.isParamWeps(quote(y<-eps1*w+ipred)))
  expect_true(.isParamWeps(quote(y<-w*eps1+f)))
  expect_true(.isParamWeps(quote(y<-eps1*w+f)))
  expect_false(.isParamWeps(quote(y<-eps1*w^2+f)))
  expect_true(.isAddW(quote(w <- theta1)))
  expect_equal(.nonmem2rx$addPar, "theta1")
  
  expect_false(.isAddW(quote(w <- f*theta1)))
  expect_false(.isAddW(quote(w <- dg1)))
  
  expect_true(.isThetaF(quote(theta1*f)))
  expect_equal(.nonmem2rx$propPar, "theta1")
  expect_equal(.nonmem2rx$curF, "f")
  expect_true(.isThetaF(quote(ipred*theta1)))
  expect_equal(.nonmem2rx$propPar, "theta1")
  expect_equal(.nonmem2rx$curF, "ipred")
  expect_false(.isThetaF(quote(ipred/theta1)))
  expect_true(.isPropW(quote(w <-theta1*f)))

  expect_true(.isAddPropW1(quote(w <- theta1*f+theta2)))
  expect_equal(.nonmem2rx$propPar, "theta1")
  expect_equal(.nonmem2rx$addPar, "theta2")
  expect_equal(.nonmem2rx$curF, "f")
  expect_false(.isAddPropW1(quote(w <- theta1*f^2+theta2)))

  expect_true(.isTheta2(quote(theta1*theta1)))
  expect_false(.isTheta2(quote(theta1*theta2)))

  expect_true(.isTheta2(quote(theta1^2)))
  expect_true(.isTheta2(quote(theta1**2.)))

  expect_true(.isTheta2(quote(ipred*ipred), useF=TRUE))
  expect_true(.isTheta2(quote(f*ipred), useF=TRUE))
  expect_true(.isTheta2(quote(f*f), useF=TRUE))
  expect_true(.isTheta2(quote(f^2), useF=TRUE))

  expect_true(.isTheta2F2(quote(f*f*theta1*theta1)))
  expect_true(.isTheta2F2(quote(f*theta1*f*theta1)))
  expect_true(.isTheta2F2(quote(f*theta1*theta1*f)))
  expect_true(.isTheta2F2(quote(theta1*f*theta1*f)))
  expect_true(.isTheta2F2(quote(theta1*theta1*f*f)))
  expect_true(.isTheta2F2(quote(theta1^2*f*f)))
  expect_true(.isTheta2F2(quote(f*theta1^2*f)))
  expect_true(.isTheta2F2(quote(f*f*theta1^2)))
  expect_true(.isTheta2F2(quote(f^2*theta1^2)))
  expect_true(.isTheta2F2(quote(theta1^2*f^2)))
  expect_false(.isTheta2F2(quote(f*f*f*theta1)))
  expect_equal(.nonmem2rx$propPar, "theta1")

  expect_true(.isAddPropW2(quote(W<-sqrt(theta1^2+theta2^2*f^2))))
  expect_equal(.nonmem2rx$propPar, "theta2")
  expect_equal(.nonmem2rx$addPar, "theta1")
  expect_equal(.nonmem2rx$curF, "f")

  expect_true(.isAddPropW2(quote(W<-sqrt(theta1^2+theta2^2*ipred^2))))
  expect_equal(.nonmem2rx$propPar, "theta2")
  expect_equal(.nonmem2rx$addPar, "theta1")
  expect_equal(.nonmem2rx$curF, "ipred")

  expect_true(.isAddPropW2(quote(W<-sqrt(theta1^2+theta2*theta2*ipred^2))))
  expect_equal(.nonmem2rx$propPar, "theta2")
  expect_equal(.nonmem2rx$addPar, "theta1")
  expect_equal(.nonmem2rx$curF, "ipred")
})
