#include <R.h>
#include <Rinternals.h>
#define printf Rprintf

/*
  Generated by Make DParser Version 1.31.4ab9d43046e5d22ffb365ec5f5184a7cfee09b30
  Available at https://github.com/jplevyak/dparser
*/

#line 7 "/home/matt/src/nonmem2rx/src/input.g.d_parser.c"
#include "dparse.h"

D_Reduction d_reduction_0_nonmem2rxInput = {1, 0, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_1_nonmem2rxInput = {1, 1, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_2_nonmem2rxInput = {2, 2, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_3_nonmem2rxInput = {1, 2, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_4_nonmem2rxInput = {1, 3, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_5_nonmem2rxInput = {1, 4, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_11_nonmem2rxInput = {3, 5, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_12_nonmem2rxInput = {3, 6, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_13_nonmem2rxInput = {1, 7, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_14_nonmem2rxInput = {1, 8, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_17_nonmem2rxInput = {3, 9, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_18_nonmem2rxInput = {1, 10, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_19_nonmem2rxInput = {2, 11, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_20_nonmem2rxInput = {1, 12, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_21_nonmem2rxInput = {0, 12, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_22_nonmem2rxInput = {1, 13, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_25_nonmem2rxInput = {1, 14, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_26_nonmem2rxInput = {2, 15, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_27_nonmem2rxInput = {0, 15, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_28_nonmem2rxInput = {1, 16, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_29_nonmem2rxInput = {2, 17, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_30_nonmem2rxInput = {1, 18, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_0_nonmem2rxInput = {19, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_1_nonmem2rxInput = {20, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_2_nonmem2rxInput = {21, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_3_nonmem2rxInput = {22, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_4_nonmem2rxInput = {23, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_5_nonmem2rxInput = {24, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_6_nonmem2rxInput = {25, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_7_nonmem2rxInput = {26, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_8_nonmem2rxInput = {27, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_9_nonmem2rxInput = {28, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_10_nonmem2rxInput = {29, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_11_nonmem2rxInput = {30, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_12_nonmem2rxInput = {31, 0, 0, 0, -4, 0, NULL};

D_Shift * d_accepts_diff_0_0_nonmem2rxInput[] = {0};
D_Shift * d_accepts_diff_0_1_nonmem2rxInput[] = {&d_shift_5_nonmem2rxInput,0};
D_Shift * d_accepts_diff_0_2_nonmem2rxInput[] = {&d_shift_3_nonmem2rxInput,0};
D_Shift * d_accepts_diff_0_3_nonmem2rxInput[] = {&d_shift_1_nonmem2rxInput,0};
D_Shift * d_accepts_diff_0_4_nonmem2rxInput[] = {&d_shift_0_nonmem2rxInput,0};
D_Shift * d_accepts_diff_0_5_nonmem2rxInput[] = {&d_shift_4_nonmem2rxInput,0};
D_Shift * d_accepts_diff_0_6_nonmem2rxInput[] = {&d_shift_2_nonmem2rxInput,0};
D_Shift ** d_accepts_diff_0_nonmem2rxInput[] = {
d_accepts_diff_0_0_nonmem2rxInput,
d_accepts_diff_0_1_nonmem2rxInput,
d_accepts_diff_0_2_nonmem2rxInput,
d_accepts_diff_0_3_nonmem2rxInput,
d_accepts_diff_0_4_nonmem2rxInput,
d_accepts_diff_0_5_nonmem2rxInput,
d_accepts_diff_0_6_nonmem2rxInput
};

unsigned char d_scanner_0_0_0_nonmem2rxInput[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_accepts_diff_0_0_0_nonmem2rxInput[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_0_1_nonmem2rxInput[SCANNER_BLOCK_SIZE] = {
0, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 
0, 2, 2, 2, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 6, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_1_0_nonmem2rxInput[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_1_1_nonmem2rxInput[SCANNER_BLOCK_SIZE] = {
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_0_1_nonmem2rxInput[] = {&d_shift_12_nonmem2rxInput,NULL};

unsigned char d_scanner_0_2_1_nonmem2rxInput[SCANNER_BLOCK_SIZE] = {
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 7, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 8, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_3_1_nonmem2rxInput[SCANNER_BLOCK_SIZE] = {
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 9, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 10, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_4_1_nonmem2rxInput[SCANNER_BLOCK_SIZE] = {
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 11, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_5_1_nonmem2rxInput[SCANNER_BLOCK_SIZE] = {
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 12, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_6_1_nonmem2rxInput[SCANNER_BLOCK_SIZE] = {
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 13, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_7_1_nonmem2rxInput[SCANNER_BLOCK_SIZE] = {
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 14, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_8_1_nonmem2rxInput[SCANNER_BLOCK_SIZE] = {
0, 2, 2, 2, 2, 2, 2, 2, 2, 15, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_9_1_nonmem2rxInput[SCANNER_BLOCK_SIZE] = {
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 
0, 2, 2, 2, 2, 2, 2, 2, 2, 16, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_10_1_nonmem2rxInput[SCANNER_BLOCK_SIZE] = {
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 17, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_11_1_nonmem2rxInput[SCANNER_BLOCK_SIZE] = {
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 
0, 2, 2, 2, 2, 2, 2, 2, 2, 18, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_12_1_nonmem2rxInput[SCANNER_BLOCK_SIZE] = {
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
19, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_13_1_nonmem2rxInput[SCANNER_BLOCK_SIZE] = {
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
20, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_14_1_nonmem2rxInput[SCANNER_BLOCK_SIZE] = {
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
21, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_15_1_nonmem2rxInput[SCANNER_BLOCK_SIZE] = {
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
22, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_16_1_nonmem2rxInput[SCANNER_BLOCK_SIZE] = {
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
23, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_17_1_nonmem2rxInput[SCANNER_BLOCK_SIZE] = {
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
24, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 
};

unsigned char d_accepts_diff_0_18_0_nonmem2rxInput[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_accepts_diff_0_18_1_nonmem2rxInput[SCANNER_BLOCK_SIZE] = {
0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 
3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 3, 
0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 
3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_0_18_nonmem2rxInput[] = {&d_shift_1_nonmem2rxInput,NULL};

unsigned char d_accepts_diff_0_19_0_nonmem2rxInput[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_accepts_diff_0_19_1_nonmem2rxInput[SCANNER_BLOCK_SIZE] = {
0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 
6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 6, 
0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 
6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_0_19_nonmem2rxInput[] = {&d_shift_2_nonmem2rxInput,NULL};

unsigned char d_accepts_diff_0_20_0_nonmem2rxInput[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_accepts_diff_0_20_1_nonmem2rxInput[SCANNER_BLOCK_SIZE] = {
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_0_20_nonmem2rxInput[] = {&d_shift_3_nonmem2rxInput,NULL};

unsigned char d_accepts_diff_0_21_0_nonmem2rxInput[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_accepts_diff_0_21_1_nonmem2rxInput[SCANNER_BLOCK_SIZE] = {
0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 
0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_0_21_nonmem2rxInput[] = {&d_shift_5_nonmem2rxInput,NULL};

unsigned char d_accepts_diff_0_22_0_nonmem2rxInput[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_accepts_diff_0_22_1_nonmem2rxInput[SCANNER_BLOCK_SIZE] = {
0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 0, 0, 4, 
0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_0_22_nonmem2rxInput[] = {&d_shift_0_nonmem2rxInput,NULL};

unsigned char d_accepts_diff_0_23_0_nonmem2rxInput[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_accepts_diff_0_23_1_nonmem2rxInput[SCANNER_BLOCK_SIZE] = {
0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 
5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 5, 
0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 
5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_0_23_nonmem2rxInput[] = {&d_shift_4_nonmem2rxInput,NULL};

D_Shift * d_accepts_diff_12_0_nonmem2rxInput[] = {0};
D_Shift ** d_accepts_diff_12_nonmem2rxInput[] = {
d_accepts_diff_12_0_nonmem2rxInput
};

unsigned char d_scanner_12_0_0_nonmem2rxInput[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 
};

D_Shift * d_shift_12_1_nonmem2rxInput[] = {&d_shift_6_nonmem2rxInput,NULL};

D_Shift * d_accepts_diff_20_0_nonmem2rxInput[] = {0};
D_Shift ** d_accepts_diff_20_nonmem2rxInput[] = {
d_accepts_diff_20_0_nonmem2rxInput
};

unsigned char d_scanner_20_0_0_nonmem2rxInput[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 
};

D_Shift * d_shift_20_1_nonmem2rxInput[] = {&d_shift_10_nonmem2rxInput,NULL};

D_Shift * d_accepts_diff_23_0_nonmem2rxInput[] = {0};
D_Shift ** d_accepts_diff_23_nonmem2rxInput[] = {
d_accepts_diff_23_0_nonmem2rxInput
};

unsigned char d_scanner_23_0_0_nonmem2rxInput[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_23_1_nonmem2rxInput[] = {&d_shift_9_nonmem2rxInput,NULL};

D_Shift * d_accepts_diff_25_0_nonmem2rxInput[] = {0};
D_Shift ** d_accepts_diff_25_nonmem2rxInput[] = {
d_accepts_diff_25_0_nonmem2rxInput
};

unsigned char d_scanner_25_0_1_nonmem2rxInput[SCANNER_BLOCK_SIZE] = {
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 
};

D_Shift * d_accepts_diff_26_0_nonmem2rxInput[] = {0};
D_Shift ** d_accepts_diff_26_nonmem2rxInput[] = {
d_accepts_diff_26_0_nonmem2rxInput
};

unsigned char d_scanner_26_0_0_nonmem2rxInput[SCANNER_BLOCK_SIZE] = {
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
};

unsigned char d_scanner_26_0_1_nonmem2rxInput[SCANNER_BLOCK_SIZE] = {
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
};

D_Shift * d_shift_26_0_nonmem2rxInput[] = {&d_shift_11_nonmem2rxInput,NULL};

SB_uint8 d_scanner_0_nonmem2rxInput[24] = {
{NULL, {d_scanner_0_0_0_nonmem2rxInput, d_scanner_0_0_1_nonmem2rxInput
 , d_scanner_0_0_0_nonmem2rxInput, d_scanner_0_0_0_nonmem2rxInput}},
{d_shift_0_1_nonmem2rxInput, {d_scanner_0_1_0_nonmem2rxInput, d_scanner_0_1_1_nonmem2rxInput
 , d_scanner_0_0_0_nonmem2rxInput, d_scanner_0_0_0_nonmem2rxInput}},
{d_shift_0_1_nonmem2rxInput, {d_scanner_0_1_0_nonmem2rxInput, d_scanner_0_2_1_nonmem2rxInput
 , d_scanner_0_0_0_nonmem2rxInput, d_scanner_0_0_0_nonmem2rxInput}},
{d_shift_0_1_nonmem2rxInput, {d_scanner_0_1_0_nonmem2rxInput, d_scanner_0_3_1_nonmem2rxInput
 , d_scanner_0_0_0_nonmem2rxInput, d_scanner_0_0_0_nonmem2rxInput}},
{d_shift_0_1_nonmem2rxInput, {d_scanner_0_1_0_nonmem2rxInput, d_scanner_0_4_1_nonmem2rxInput
 , d_scanner_0_0_0_nonmem2rxInput, d_scanner_0_0_0_nonmem2rxInput}},
{d_shift_0_1_nonmem2rxInput, {d_scanner_0_1_0_nonmem2rxInput, d_scanner_0_5_1_nonmem2rxInput
 , d_scanner_0_0_0_nonmem2rxInput, d_scanner_0_0_0_nonmem2rxInput}},
{d_shift_0_1_nonmem2rxInput, {d_scanner_0_1_0_nonmem2rxInput, d_scanner_0_6_1_nonmem2rxInput
 , d_scanner_0_0_0_nonmem2rxInput, d_scanner_0_0_0_nonmem2rxInput}},
{d_shift_0_1_nonmem2rxInput, {d_scanner_0_1_0_nonmem2rxInput, d_scanner_0_7_1_nonmem2rxInput
 , d_scanner_0_0_0_nonmem2rxInput, d_scanner_0_0_0_nonmem2rxInput}},
{d_shift_0_1_nonmem2rxInput, {d_scanner_0_1_0_nonmem2rxInput, d_scanner_0_8_1_nonmem2rxInput
 , d_scanner_0_0_0_nonmem2rxInput, d_scanner_0_0_0_nonmem2rxInput}},
{d_shift_0_1_nonmem2rxInput, {d_scanner_0_1_0_nonmem2rxInput, d_scanner_0_9_1_nonmem2rxInput
 , d_scanner_0_0_0_nonmem2rxInput, d_scanner_0_0_0_nonmem2rxInput}},
{d_shift_0_1_nonmem2rxInput, {d_scanner_0_1_0_nonmem2rxInput, d_scanner_0_10_1_nonmem2rxInput
 , d_scanner_0_0_0_nonmem2rxInput, d_scanner_0_0_0_nonmem2rxInput}},
{d_shift_0_1_nonmem2rxInput, {d_scanner_0_1_0_nonmem2rxInput, d_scanner_0_11_1_nonmem2rxInput
 , d_scanner_0_0_0_nonmem2rxInput, d_scanner_0_0_0_nonmem2rxInput}},
{d_shift_0_1_nonmem2rxInput, {d_scanner_0_1_0_nonmem2rxInput, d_scanner_0_12_1_nonmem2rxInput
 , d_scanner_0_0_0_nonmem2rxInput, d_scanner_0_0_0_nonmem2rxInput}},
{d_shift_0_1_nonmem2rxInput, {d_scanner_0_1_0_nonmem2rxInput, d_scanner_0_13_1_nonmem2rxInput
 , d_scanner_0_0_0_nonmem2rxInput, d_scanner_0_0_0_nonmem2rxInput}},
{d_shift_0_1_nonmem2rxInput, {d_scanner_0_1_0_nonmem2rxInput, d_scanner_0_14_1_nonmem2rxInput
 , d_scanner_0_0_0_nonmem2rxInput, d_scanner_0_0_0_nonmem2rxInput}},
{d_shift_0_1_nonmem2rxInput, {d_scanner_0_1_0_nonmem2rxInput, d_scanner_0_15_1_nonmem2rxInput
 , d_scanner_0_0_0_nonmem2rxInput, d_scanner_0_0_0_nonmem2rxInput}},
{d_shift_0_1_nonmem2rxInput, {d_scanner_0_1_0_nonmem2rxInput, d_scanner_0_16_1_nonmem2rxInput
 , d_scanner_0_0_0_nonmem2rxInput, d_scanner_0_0_0_nonmem2rxInput}},
{d_shift_0_1_nonmem2rxInput, {d_scanner_0_1_0_nonmem2rxInput, d_scanner_0_17_1_nonmem2rxInput
 , d_scanner_0_0_0_nonmem2rxInput, d_scanner_0_0_0_nonmem2rxInput}},
{d_shift_0_18_nonmem2rxInput, {d_scanner_0_1_0_nonmem2rxInput, d_scanner_0_1_1_nonmem2rxInput
 , d_scanner_0_0_0_nonmem2rxInput, d_scanner_0_0_0_nonmem2rxInput}},
{d_shift_0_19_nonmem2rxInput, {d_scanner_0_1_0_nonmem2rxInput, d_scanner_0_1_1_nonmem2rxInput
 , d_scanner_0_0_0_nonmem2rxInput, d_scanner_0_0_0_nonmem2rxInput}},
{d_shift_0_20_nonmem2rxInput, {d_scanner_0_1_0_nonmem2rxInput, d_scanner_0_1_1_nonmem2rxInput
 , d_scanner_0_0_0_nonmem2rxInput, d_scanner_0_0_0_nonmem2rxInput}},
{d_shift_0_21_nonmem2rxInput, {d_scanner_0_1_0_nonmem2rxInput, d_scanner_0_1_1_nonmem2rxInput
 , d_scanner_0_0_0_nonmem2rxInput, d_scanner_0_0_0_nonmem2rxInput}},
{d_shift_0_22_nonmem2rxInput, {d_scanner_0_1_0_nonmem2rxInput, d_scanner_0_1_1_nonmem2rxInput
 , d_scanner_0_0_0_nonmem2rxInput, d_scanner_0_0_0_nonmem2rxInput}},
{d_shift_0_23_nonmem2rxInput, {d_scanner_0_1_0_nonmem2rxInput, d_scanner_0_1_1_nonmem2rxInput
 , d_scanner_0_0_0_nonmem2rxInput, d_scanner_0_0_0_nonmem2rxInput}}
};

SB_trans_uint8 d_transition_0_nonmem2rxInput[24] = {
{{d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput
 , d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput}},
{{d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput
 , d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput}},
{{d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput
 , d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput}},
{{d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput
 , d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput}},
{{d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput
 , d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput}},
{{d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput
 , d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput}},
{{d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput
 , d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput}},
{{d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput
 , d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput}},
{{d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput
 , d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput}},
{{d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput
 , d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput}},
{{d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput
 , d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput}},
{{d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput
 , d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput}},
{{d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput
 , d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput}},
{{d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput
 , d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput}},
{{d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput
 , d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput}},
{{d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput
 , d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput}},
{{d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput
 , d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput}},
{{d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput
 , d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput}},
{{d_accepts_diff_0_18_0_nonmem2rxInput, d_accepts_diff_0_18_1_nonmem2rxInput
 , d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput}},
{{d_accepts_diff_0_19_0_nonmem2rxInput, d_accepts_diff_0_19_1_nonmem2rxInput
 , d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput}},
{{d_accepts_diff_0_20_0_nonmem2rxInput, d_accepts_diff_0_20_1_nonmem2rxInput
 , d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput}},
{{d_accepts_diff_0_21_0_nonmem2rxInput, d_accepts_diff_0_21_1_nonmem2rxInput
 , d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput}},
{{d_accepts_diff_0_22_0_nonmem2rxInput, d_accepts_diff_0_22_1_nonmem2rxInput
 , d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput}},
{{d_accepts_diff_0_23_0_nonmem2rxInput, d_accepts_diff_0_23_1_nonmem2rxInput
 , d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput}}
};

SB_uint8 d_scanner_12_nonmem2rxInput[2] = {
{NULL, {d_scanner_12_0_0_nonmem2rxInput, d_scanner_0_0_0_nonmem2rxInput
 , d_scanner_0_0_0_nonmem2rxInput, d_scanner_0_0_0_nonmem2rxInput}},
{d_shift_12_1_nonmem2rxInput, {d_scanner_0_0_0_nonmem2rxInput, d_scanner_0_0_0_nonmem2rxInput
 , d_scanner_0_0_0_nonmem2rxInput, d_scanner_0_0_0_nonmem2rxInput}}
};

SB_trans_uint8 d_transition_12_nonmem2rxInput[2] = {
{{d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput
 , d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput}},
{{d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput
 , d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput}}
};

SB_uint8 d_scanner_20_nonmem2rxInput[2] = {
{NULL, {d_scanner_20_0_0_nonmem2rxInput, d_scanner_0_0_0_nonmem2rxInput
 , d_scanner_0_0_0_nonmem2rxInput, d_scanner_0_0_0_nonmem2rxInput}},
{d_shift_20_1_nonmem2rxInput, {d_scanner_0_0_0_nonmem2rxInput, d_scanner_0_0_0_nonmem2rxInput
 , d_scanner_0_0_0_nonmem2rxInput, d_scanner_0_0_0_nonmem2rxInput}}
};

SB_trans_uint8 d_transition_20_nonmem2rxInput[2] = {
{{d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput
 , d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput}},
{{d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput
 , d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput}}
};

SB_uint8 d_scanner_23_nonmem2rxInput[2] = {
{NULL, {d_scanner_23_0_0_nonmem2rxInput, d_scanner_0_0_0_nonmem2rxInput
 , d_scanner_0_0_0_nonmem2rxInput, d_scanner_0_0_0_nonmem2rxInput}},
{d_shift_23_1_nonmem2rxInput, {d_scanner_23_0_0_nonmem2rxInput, d_scanner_0_0_0_nonmem2rxInput
 , d_scanner_0_0_0_nonmem2rxInput, d_scanner_0_0_0_nonmem2rxInput}}
};

SB_trans_uint8 d_transition_23_nonmem2rxInput[2] = {
{{d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput
 , d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput}},
{{d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput
 , d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput}}
};

SB_uint8 d_scanner_25_nonmem2rxInput[2] = {
{NULL, {d_scanner_0_0_0_nonmem2rxInput, d_scanner_25_0_1_nonmem2rxInput
 , d_scanner_0_0_0_nonmem2rxInput, d_scanner_0_0_0_nonmem2rxInput}},
{d_shift_0_1_nonmem2rxInput, {d_scanner_0_1_0_nonmem2rxInput, d_scanner_0_1_1_nonmem2rxInput
 , d_scanner_0_0_0_nonmem2rxInput, d_scanner_0_0_0_nonmem2rxInput}}
};

SB_trans_uint8 d_transition_25_nonmem2rxInput[2] = {
{{d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput
 , d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput}},
{{d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput
 , d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput}}
};

SB_uint8 d_scanner_26_nonmem2rxInput[2] = {
{d_shift_26_0_nonmem2rxInput, {d_scanner_26_0_0_nonmem2rxInput, d_scanner_26_0_1_nonmem2rxInput
 , d_scanner_26_0_1_nonmem2rxInput, d_scanner_26_0_1_nonmem2rxInput}},
{d_shift_26_0_nonmem2rxInput, {d_scanner_26_0_0_nonmem2rxInput, d_scanner_26_0_1_nonmem2rxInput
 , d_scanner_26_0_1_nonmem2rxInput, d_scanner_26_0_1_nonmem2rxInput}}
};

SB_trans_uint8 d_transition_26_nonmem2rxInput[2] = {
{{d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput
 , d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput}},
{{d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput
 , d_accepts_diff_0_0_0_nonmem2rxInput, d_accepts_diff_0_0_0_nonmem2rxInput}}
};

unsigned char d_goto_valid_0_nonmem2rxInput[] = {
0xfe,0x2f,0xfc,0x81};
unsigned char d_goto_valid_1_nonmem2rxInput[] = {
0x0,0xc0,0x0,0x0};
D_Reduction * d_reductions_1_nonmem2rxInput[] = {&d_reduction_27_nonmem2rxInput};
D_RightEpsilonHint d_right_epsilon_hints_1_nonmem2rxInput[] = {{0, 23, &d_reduction_25_nonmem2rxInput}};
D_Reduction * d_reductions_2_nonmem2rxInput[] = {&d_reduction_5_nonmem2rxInput};
D_Reduction * d_reductions_3_nonmem2rxInput[] = {&d_reduction_5_nonmem2rxInput};
D_Reduction * d_reductions_4_nonmem2rxInput[] = {&d_reduction_5_nonmem2rxInput};
D_Reduction * d_reductions_5_nonmem2rxInput[] = {&d_reduction_5_nonmem2rxInput};
D_Reduction * d_reductions_6_nonmem2rxInput[] = {&d_reduction_5_nonmem2rxInput};
D_Reduction * d_reductions_7_nonmem2rxInput[] = {&d_reduction_5_nonmem2rxInput};
D_Reduction * d_reductions_8_nonmem2rxInput[] = {&d_reduction_30_nonmem2rxInput};
unsigned char d_goto_valid_10_nonmem2rxInput[] = {
0xf8,0x2f,0xfc,0x81};
D_Reduction * d_reductions_10_nonmem2rxInput[] = {&d_reduction_1_nonmem2rxInput};
D_Reduction * d_reductions_11_nonmem2rxInput[] = {&d_reduction_3_nonmem2rxInput};
unsigned char d_goto_valid_12_nonmem2rxInput[] = {
0x0,0x0,0x0,0x2};
D_Reduction * d_reductions_12_nonmem2rxInput[] = {&d_reduction_13_nonmem2rxInput};
D_Reduction * d_reductions_13_nonmem2rxInput[] = {&d_reduction_14_nonmem2rxInput};
D_Reduction * d_reductions_14_nonmem2rxInput[] = {&d_reduction_14_nonmem2rxInput};
D_Reduction * d_reductions_15_nonmem2rxInput[] = {&d_reduction_14_nonmem2rxInput};
D_Reduction * d_reductions_16_nonmem2rxInput[] = {&d_reduction_22_nonmem2rxInput};
D_Reduction * d_reductions_17_nonmem2rxInput[] = {&d_reduction_22_nonmem2rxInput};
D_Reduction * d_reductions_18_nonmem2rxInput[] = {&d_reduction_22_nonmem2rxInput};
D_Reduction * d_reductions_19_nonmem2rxInput[] = {&d_reduction_4_nonmem2rxInput};
unsigned char d_goto_valid_20_nonmem2rxInput[] = {
0x0,0x10,0x2,0x20};
D_Reduction * d_reductions_20_nonmem2rxInput[] = {&d_reduction_21_nonmem2rxInput};
D_RightEpsilonHint d_right_epsilon_hints_20_nonmem2rxInput[] = {{0, 27, &d_reduction_19_nonmem2rxInput}};
unsigned char d_goto_valid_21_nonmem2rxInput[] = {
0x0,0x0,0x0,0x2};
D_Reduction * d_reductions_21_nonmem2rxInput[] = {&d_reduction_18_nonmem2rxInput};
unsigned char d_goto_valid_23_nonmem2rxInput[] = {
0x0,0x0,0x1,0x10};
D_Reduction * d_reductions_23_nonmem2rxInput[] = {&d_reduction_25_nonmem2rxInput};
D_Reduction * d_reductions_24_nonmem2rxInput[] = {&d_reduction_2_nonmem2rxInput};
unsigned char d_goto_valid_25_nonmem2rxInput[] = {
0x0,0x0,0x4,0x80};
unsigned char d_goto_valid_26_nonmem2rxInput[] = {
0x0,0x0,0x0,0x40};
D_Reduction * d_reductions_27_nonmem2rxInput[] = {&d_reduction_19_nonmem2rxInput};
D_Reduction * d_reductions_28_nonmem2rxInput[] = {&d_reduction_20_nonmem2rxInput};
unsigned char d_goto_valid_29_nonmem2rxInput[] = {
0x10,0x0,0xfc,0x81};
D_Reduction * d_reductions_30_nonmem2rxInput[] = {&d_reduction_28_nonmem2rxInput};
D_Reduction * d_reductions_31_nonmem2rxInput[] = {&d_reduction_26_nonmem2rxInput};
D_Reduction * d_reductions_32_nonmem2rxInput[] = {&d_reduction_11_nonmem2rxInput};
D_Reduction * d_reductions_33_nonmem2rxInput[] = {&d_reduction_29_nonmem2rxInput};
D_Reduction * d_reductions_34_nonmem2rxInput[] = {&d_reduction_12_nonmem2rxInput};
D_Reduction * d_reductions_35_nonmem2rxInput[] = {&d_reduction_17_nonmem2rxInput};
unsigned short d_gotos_nonmem2rxInput[81] = {
10,11,12,13,14,15,16,17,18,19,20,26,21,23,24,30,
32,22,3,4,5,6,7,8,34,0,0,0,31,33,9,25,
13,14,15,16,17,18,19,20,28,21,9,0,0,29,22,3,
4,5,6,7,8,35,0,0,0,27,0,9,0,0,0,0,
0,0,0,36,3,4,5,6,7,8,0,0,0,0,0,0,
9};


D_State d_states_nonmem2rxInput[] = {
{d_goto_valid_0_nonmem2rxInput, 1, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_0_nonmem2rxInput, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_0_nonmem2rxInput, d_accepts_diff_0_nonmem2rxInput, -1},
{d_goto_valid_1_nonmem2rxInput, 1, {1, d_reductions_1_nonmem2rxInput}, {1, d_right_epsilon_hints_1_nonmem2rxInput}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_2_nonmem2rxInput}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_3_nonmem2rxInput}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_4_nonmem2rxInput}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_5_nonmem2rxInput}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_6_nonmem2rxInput}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_7_nonmem2rxInput}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_8_nonmem2rxInput}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {0, NULL}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 1, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_10_nonmem2rxInput, -28, {1, d_reductions_10_nonmem2rxInput}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_0_nonmem2rxInput, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_0_nonmem2rxInput, d_accepts_diff_0_nonmem2rxInput, -1},
{NULL, -2147483647, {1, d_reductions_11_nonmem2rxInput}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_12_nonmem2rxInput, 14, {1, d_reductions_12_nonmem2rxInput}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_12_nonmem2rxInput, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_12_nonmem2rxInput, d_accepts_diff_12_nonmem2rxInput, -1},
{NULL, -2147483647, {1, d_reductions_13_nonmem2rxInput}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_14_nonmem2rxInput}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_15_nonmem2rxInput}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_16_nonmem2rxInput}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_17_nonmem2rxInput}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_18_nonmem2rxInput}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_19_nonmem2rxInput}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_20_nonmem2rxInput, -28, {1, d_reductions_20_nonmem2rxInput}, {1, d_right_epsilon_hints_20_nonmem2rxInput}, {0, NULL}, 1, NULL, (void*)d_scanner_20_nonmem2rxInput, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_20_nonmem2rxInput, d_accepts_diff_20_nonmem2rxInput, -1},
{d_goto_valid_21_nonmem2rxInput, 10, {1, d_reductions_21_nonmem2rxInput}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_12_nonmem2rxInput, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_12_nonmem2rxInput, d_accepts_diff_12_nonmem2rxInput, -1},
{NULL, -2147483647, {0, NULL}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 1, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_23_nonmem2rxInput, 0, {1, d_reductions_23_nonmem2rxInput}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_23_nonmem2rxInput, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_23_nonmem2rxInput, d_accepts_diff_23_nonmem2rxInput, -1},
{NULL, -2147483647, {1, d_reductions_24_nonmem2rxInput}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_25_nonmem2rxInput, -11, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_25_nonmem2rxInput, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_25_nonmem2rxInput, d_accepts_diff_25_nonmem2rxInput, -1},
{d_goto_valid_26_nonmem2rxInput, 6, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_26_nonmem2rxInput, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_26_nonmem2rxInput, d_accepts_diff_26_nonmem2rxInput, -1},
{NULL, -2147483647, {1, d_reductions_27_nonmem2rxInput}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_28_nonmem2rxInput}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_29_nonmem2rxInput, -49, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_0_nonmem2rxInput, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_0_nonmem2rxInput, d_accepts_diff_0_nonmem2rxInput, -1},
{NULL, -2147483647, {1, d_reductions_30_nonmem2rxInput}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_31_nonmem2rxInput}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_32_nonmem2rxInput}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_33_nonmem2rxInput}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_34_nonmem2rxInput}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_35_nonmem2rxInput}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1}
};

D_Symbol d_symbols_nonmem2rxInput[] = {
{D_SYMBOL_EBNF, "0 Start", 7, -1},
{D_SYMBOL_NTERM, "statement_list", 14, -1},
{D_SYMBOL_INTERNAL, "statement_list__3", 17, -1},
{D_SYMBOL_EBNF, "statement_list__2", 17, -1},
{D_SYMBOL_NTERM, "drop_keyword", 12, -1},
{D_SYMBOL_NTERM, "drop1", 5, -1},
{D_SYMBOL_NTERM, "drop2", 5, -1},
{D_SYMBOL_NTERM, "drop3", 5, -1},
{D_SYMBOL_NTERM, "drop_item", 9, -1},
{D_SYMBOL_NTERM, "alias_item", 10, -1},
{D_SYMBOL_NTERM, "reg_item", 8, -1},
{D_SYMBOL_NTERM, "statement", 9, -1},
{D_SYMBOL_INTERNAL, "statement__13", 13, -1},
{D_SYMBOL_EBNF, "statement__12", 13, -1},
{D_SYMBOL_NTERM, "whitespace", 10, 1},
{D_SYMBOL_INTERNAL, "whitespace__16", 14, -1},
{D_SYMBOL_EBNF, "whitespace__15", 14, -1},
{D_SYMBOL_NTERM, "singleLineComment", 17, -1},
{D_SYMBOL_NTERM, "identifier_nm", 13, -1},
{D_SYMBOL_STRING, "drop", 4, -1},
{D_SYMBOL_STRING, "DROP", 4, -1},
{D_SYMBOL_STRING, "Drop", 4, -1},
{D_SYMBOL_STRING, "SKIP", 4, -1},
{D_SYMBOL_STRING, "skip", 4, -1},
{D_SYMBOL_STRING, "Skip", 4, -1},
{D_SYMBOL_STRING, "=", 1, -1},
{D_SYMBOL_STRING, "=", 1, -1},
{D_SYMBOL_STRING, "=", 1, -1},
{D_SYMBOL_REGEX, "[ \\t\\r\\n]+", 13, -1},
{D_SYMBOL_STRING, ";", 1, -1},
{D_SYMBOL_REGEX, "[^\\n]*", 7, -1},
{D_SYMBOL_REGEX, "[a-zA-Z][a-zA-Z0-9_]*", 21, -1},
};

D_ParserTables parser_tables_nonmem2rxInput = {
36, d_states_nonmem2rxInput, d_gotos_nonmem2rxInput, 1, 32, d_symbols_nonmem2rxInput, NULL, 0, NULL, 0};
