#include <R.h>
#include <Rinternals.h>
#define printf Rprintf

/*
  Generated by Make DParser Version 1.31.4ab9d43046e5d22ffb365ec5f5184a7cfee09b30
  Available at https://github.com/jplevyak/dparser
*/

#line 7 "C:/R/nonmem2rx/src/omega.g.d_parser.c"
#include "dparse.h"

D_Reduction d_reduction_0_nonmem2rxOmega = {1, 0, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_1_nonmem2rxOmega = {2, 1, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_2_nonmem2rxOmega = {2, 2, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_3_nonmem2rxOmega = {1, 2, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_4_nonmem2rxOmega = {1, 3, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_5_nonmem2rxOmega = {1, 4, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_6_nonmem2rxOmega = {0, 4, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_7_nonmem2rxOmega = {4, 5, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_8_nonmem2rxOmega = {1, 6, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_10_nonmem2rxOmega = {1, 7, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_11_nonmem2rxOmega = {1, 8, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_13_nonmem2rxOmega = {4, 9, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_14_nonmem2rxOmega = {1, 10, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_16_nonmem2rxOmega = {2, 11, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_17_nonmem2rxOmega = {2, 12, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_18_nonmem2rxOmega = {1, 13, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_23_nonmem2rxOmega = {1, 14, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_25_nonmem2rxOmega = {1, 15, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_26_nonmem2rxOmega = {0, 15, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_27_nonmem2rxOmega = {3, 16, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_28_nonmem2rxOmega = {1, 17, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_29_nonmem2rxOmega = {0, 17, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_30_nonmem2rxOmega = {2, 18, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_31_nonmem2rxOmega = {0, 18, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_32_nonmem2rxOmega = {1, 19, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_35_nonmem2rxOmega = {2, 20, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_36_nonmem2rxOmega = {1, 21, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_37_nonmem2rxOmega = {0, 21, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_38_nonmem2rxOmega = {3, 22, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_39_nonmem2rxOmega = {4, 23, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_40_nonmem2rxOmega = {1, 24, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_44_nonmem2rxOmega = {2, 25, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_45_nonmem2rxOmega = {1, 26, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_46_nonmem2rxOmega = {0, 26, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_47_nonmem2rxOmega = {1, 27, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_50_nonmem2rxOmega = {1, 28, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_51_nonmem2rxOmega = {2, 29, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_52_nonmem2rxOmega = {0, 29, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_53_nonmem2rxOmega = {1, 30, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_54_nonmem2rxOmega = {2, 31, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_55_nonmem2rxOmega = {1, 32, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_56_nonmem2rxOmega = {1, 33, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_57_nonmem2rxOmega = {1, 34, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_0_nonmem2rxOmega = {35, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_1_nonmem2rxOmega = {36, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_2_nonmem2rxOmega = {37, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_3_nonmem2rxOmega = {38, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_4_nonmem2rxOmega = {39, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_5_nonmem2rxOmega = {40, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_6_nonmem2rxOmega = {41, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_7_nonmem2rxOmega = {42, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_8_nonmem2rxOmega = {43, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_9_nonmem2rxOmega = {44, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_10_nonmem2rxOmega = {45, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_11_nonmem2rxOmega = {46, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_12_nonmem2rxOmega = {47, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_13_nonmem2rxOmega = {48, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_14_nonmem2rxOmega = {49, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_15_nonmem2rxOmega = {50, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_16_nonmem2rxOmega = {51, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_17_nonmem2rxOmega = {52, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_18_nonmem2rxOmega = {53, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_19_nonmem2rxOmega = {54, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_20_nonmem2rxOmega = {55, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_21_nonmem2rxOmega = {56, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_22_nonmem2rxOmega = {57, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_23_nonmem2rxOmega = {58, 0, 0, 0, -1, 0, NULL};
D_Shift d_shift_24_nonmem2rxOmega = {59, 0, 0, 0, -2, 0, NULL};
D_Shift d_shift_25_nonmem2rxOmega = {60, 0, 0, 0, -3, 0, NULL};

D_Shift * d_accepts_diff_0_0_nonmem2rxOmega[] = {0};
D_Shift ** d_accepts_diff_0_nonmem2rxOmega[] = {
d_accepts_diff_0_0_nonmem2rxOmega
};

unsigned char d_scanner_0_0_0_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_accepts_diff_0_0_0_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_0_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 2, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 4, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_1_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_2_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_3_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_4_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_5_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_6_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_7_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_8_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_9_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 14, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_10_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 15, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_11_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_12_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 17, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_13_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 18, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_14_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 19, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_15_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 20, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_16_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 21, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_0_17_nonmem2rxOmega[] = {&d_shift_5_nonmem2rxOmega,NULL};

unsigned char d_scanner_0_18_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 22, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_0_19_nonmem2rxOmega[] = {&d_shift_4_nonmem2rxOmega,NULL};

unsigned char d_scanner_0_20_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 23, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_21_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 24, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_22_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 25, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_23_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 26, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_24_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 27, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_0_25_nonmem2rxOmega[] = {&d_shift_1_nonmem2rxOmega,NULL};

D_Shift * d_shift_0_26_nonmem2rxOmega[] = {&d_shift_0_nonmem2rxOmega,NULL};

D_Shift * d_accepts_diff_7_0_nonmem2rxOmega[] = {0};
D_Shift ** d_accepts_diff_7_nonmem2rxOmega[] = {
d_accepts_diff_7_0_nonmem2rxOmega
};

unsigned char d_scanner_7_0_0_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 3, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 
};

D_Shift * d_shift_7_1_nonmem2rxOmega[] = {&d_shift_2_nonmem2rxOmega,NULL};

D_Shift * d_shift_7_2_nonmem2rxOmega[] = {&d_shift_19_nonmem2rxOmega,NULL};

D_Shift * d_shift_7_3_nonmem2rxOmega[] = {&d_shift_21_nonmem2rxOmega,NULL};

D_Shift * d_accepts_diff_9_0_nonmem2rxOmega[] = {0};
D_Shift ** d_accepts_diff_9_nonmem2rxOmega[] = {
d_accepts_diff_9_0_nonmem2rxOmega
};

unsigned char d_scanner_9_0_0_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_accepts_diff_10_0_nonmem2rxOmega[] = {0};
D_Shift ** d_accepts_diff_10_nonmem2rxOmega[] = {
d_accepts_diff_10_0_nonmem2rxOmega
};

unsigned char d_scanner_10_0_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_10_2_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_10_3_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_10_4_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_10_5_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_10_6_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_10_7_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_10_8_nonmem2rxOmega[] = {&d_shift_8_nonmem2rxOmega,NULL};

D_Shift * d_shift_10_9_nonmem2rxOmega[] = {&d_shift_9_nonmem2rxOmega,NULL};

D_Shift * d_accepts_diff_12_0_nonmem2rxOmega[] = {0};
D_Shift ** d_accepts_diff_12_nonmem2rxOmega[] = {
d_accepts_diff_12_0_nonmem2rxOmega
};

unsigned char d_scanner_12_0_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_12_1_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_12_2_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_12_3_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_12_4_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_12_5_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_12_6_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_accepts_diff_17_0_nonmem2rxOmega[] = {0};
D_Shift ** d_accepts_diff_17_nonmem2rxOmega[] = {
d_accepts_diff_17_0_nonmem2rxOmega
};

unsigned char d_scanner_17_0_0_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_17_1_nonmem2rxOmega[] = {&d_shift_20_nonmem2rxOmega,NULL};

D_Shift * d_accepts_diff_18_0_nonmem2rxOmega[] = {0};
D_Shift * d_accepts_diff_18_1_nonmem2rxOmega[] = {&d_shift_18_nonmem2rxOmega,0};
D_Shift * d_accepts_diff_18_2_nonmem2rxOmega[] = {&d_shift_17_nonmem2rxOmega,0};
D_Shift ** d_accepts_diff_18_nonmem2rxOmega[] = {
d_accepts_diff_18_0_nonmem2rxOmega,
d_accepts_diff_18_1_nonmem2rxOmega,
d_accepts_diff_18_2_nonmem2rxOmega
};

unsigned char d_scanner_18_0_0_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_18_0_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_18_2_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_18_3_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_18_4_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_18_5_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_accepts_diff_18_6_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_18_6_nonmem2rxOmega[] = {&d_shift_17_nonmem2rxOmega,NULL};

unsigned char d_accepts_diff_18_7_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_18_7_nonmem2rxOmega[] = {&d_shift_18_nonmem2rxOmega,NULL};

unsigned char d_scanner_18_8_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_18_9_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_18_10_nonmem2rxOmega[] = {&d_shift_16_nonmem2rxOmega,NULL};

D_Shift * d_shift_18_11_nonmem2rxOmega[] = {&d_shift_15_nonmem2rxOmega,NULL};

D_Shift * d_accepts_diff_20_0_nonmem2rxOmega[] = {0};
D_Shift ** d_accepts_diff_20_nonmem2rxOmega[] = {
d_accepts_diff_20_0_nonmem2rxOmega
};

unsigned char d_scanner_20_0_0_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
};

unsigned char d_scanner_20_0_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
};

D_Shift * d_shift_20_0_nonmem2rxOmega[] = {&d_shift_22_nonmem2rxOmega,NULL};

D_Shift * d_accepts_diff_30_0_nonmem2rxOmega[] = {0};
D_Shift * d_accepts_diff_30_1_nonmem2rxOmega[] = {&d_shift_18_nonmem2rxOmega,0};
D_Shift * d_accepts_diff_30_2_nonmem2rxOmega[] = {&d_shift_17_nonmem2rxOmega,0};
D_Shift ** d_accepts_diff_30_nonmem2rxOmega[] = {
d_accepts_diff_30_0_nonmem2rxOmega,
d_accepts_diff_30_1_nonmem2rxOmega,
d_accepts_diff_30_2_nonmem2rxOmega
};

unsigned char d_scanner_30_0_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_30_1_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_30_2_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_30_3_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_30_4_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_30_7_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_30_8_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_accepts_diff_31_0_nonmem2rxOmega[] = {0};
D_Shift * d_accepts_diff_31_1_nonmem2rxOmega[] = {&d_shift_23_nonmem2rxOmega,0};
D_Shift ** d_accepts_diff_31_nonmem2rxOmega[] = {
d_accepts_diff_31_0_nonmem2rxOmega,
d_accepts_diff_31_1_nonmem2rxOmega
};

unsigned char d_scanner_31_0_0_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 
3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_31_1_0_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_31_2_0_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 
7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_accepts_diff_31_2_0_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_31_2_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_accepts_diff_31_2_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_31_2_nonmem2rxOmega[] = {&d_shift_23_nonmem2rxOmega,NULL};

unsigned char d_scanner_31_3_0_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 
4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_accepts_diff_31_3_0_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_31_4_1_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_31_4_nonmem2rxOmega[] = {&d_shift_24_nonmem2rxOmega,NULL};

unsigned char d_scanner_31_5_0_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_31_7_0_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 0, 11, 0, 0, 
12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_31_8_0_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 13, 0, 13, 0, 0, 
14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_31_10_0_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_31_11_nonmem2rxOmega[] = {&d_shift_25_nonmem2rxOmega,NULL};

unsigned char d_scanner_31_12_0_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_accepts_diff_33_0_nonmem2rxOmega[] = {0};
D_Shift ** d_accepts_diff_33_nonmem2rxOmega[] = {
d_accepts_diff_33_0_nonmem2rxOmega
};

unsigned char d_scanner_33_0_0_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_33_2_0_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_accepts_diff_45_0_nonmem2rxOmega[] = {0};
D_Shift ** d_accepts_diff_45_nonmem2rxOmega[] = {
d_accepts_diff_45_0_nonmem2rxOmega
};

unsigned char d_scanner_45_0_0_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_45_1_nonmem2rxOmega[] = {&d_shift_3_nonmem2rxOmega,NULL};

D_Shift * d_accepts_diff_46_0_nonmem2rxOmega[] = {0};
D_Shift ** d_accepts_diff_46_nonmem2rxOmega[] = {
d_accepts_diff_46_0_nonmem2rxOmega
};

D_Shift * d_accepts_diff_49_0_nonmem2rxOmega[] = {0};
D_Shift ** d_accepts_diff_49_nonmem2rxOmega[] = {
d_accepts_diff_49_0_nonmem2rxOmega
};

unsigned char d_scanner_49_0_0_nonmem2rxOmega[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 
};

D_Shift * d_shift_49_1_nonmem2rxOmega[] = {&d_shift_10_nonmem2rxOmega,NULL};

SB_uint8 d_scanner_0_nonmem2rxOmega[27] = {
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_1_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_2_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_3_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_4_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_5_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_6_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_7_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_8_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_9_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_10_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_11_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_12_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_13_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_14_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_15_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_16_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{d_shift_0_17_nonmem2rxOmega, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_18_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{d_shift_0_19_nonmem2rxOmega, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_20_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_21_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_22_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_23_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_24_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{d_shift_0_25_nonmem2rxOmega, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{d_shift_0_26_nonmem2rxOmega, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}}
};

SB_trans_uint8 d_transition_0_nonmem2rxOmega[27] = {
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}}
};

SB_uint8 d_scanner_7_nonmem2rxOmega[4] = {
{NULL, {d_scanner_7_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{d_shift_7_1_nonmem2rxOmega, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{d_shift_7_2_nonmem2rxOmega, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{d_shift_7_3_nonmem2rxOmega, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}}
};

SB_trans_uint8 d_transition_7_nonmem2rxOmega[4] = {
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}}
};

SB_uint8 d_scanner_9_nonmem2rxOmega[2] = {
{NULL, {d_scanner_9_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{d_shift_7_1_nonmem2rxOmega, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}}
};

SB_trans_uint8 d_transition_9_nonmem2rxOmega[2] = {
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}}
};

SB_uint8 d_scanner_10_nonmem2rxOmega[10] = {
{NULL, {d_scanner_9_0_0_nonmem2rxOmega, d_scanner_10_0_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{d_shift_7_1_nonmem2rxOmega, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_10_2_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_10_3_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_10_4_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_10_5_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_10_6_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_10_7_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{d_shift_10_8_nonmem2rxOmega, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{d_shift_10_9_nonmem2rxOmega, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}}
};

SB_trans_uint8 d_transition_10_nonmem2rxOmega[10] = {
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}}
};

SB_uint8 d_scanner_12_nonmem2rxOmega[9] = {
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_12_0_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_12_1_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_12_2_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_12_3_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_12_4_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_12_5_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_12_6_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{d_shift_10_8_nonmem2rxOmega, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{d_shift_10_9_nonmem2rxOmega, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}}
};

SB_trans_uint8 d_transition_12_nonmem2rxOmega[9] = {
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}}
};

SB_uint8 d_scanner_17_nonmem2rxOmega[2] = {
{NULL, {d_scanner_17_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{d_shift_17_1_nonmem2rxOmega, {d_scanner_17_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}}
};

SB_trans_uint8 d_transition_17_nonmem2rxOmega[2] = {
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}}
};

SB_uint8 d_scanner_18_nonmem2rxOmega[12] = {
{NULL, {d_scanner_18_0_0_nonmem2rxOmega, d_scanner_18_0_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{d_shift_7_2_nonmem2rxOmega, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_18_2_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_18_3_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_18_4_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_18_5_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{d_shift_18_6_nonmem2rxOmega, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_10_6_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{d_shift_18_7_nonmem2rxOmega, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_10_7_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_18_8_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_18_9_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{d_shift_18_10_nonmem2rxOmega, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{d_shift_18_11_nonmem2rxOmega, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}}
};

SB_trans_uint8 d_transition_18_nonmem2rxOmega[12] = {
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_18_6_1_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_18_7_1_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}}
};

SB_uint8 d_scanner_20_nonmem2rxOmega[2] = {
{d_shift_20_0_nonmem2rxOmega, {d_scanner_20_0_0_nonmem2rxOmega, d_scanner_20_0_1_nonmem2rxOmega
 , d_scanner_20_0_1_nonmem2rxOmega, d_scanner_20_0_1_nonmem2rxOmega}},
{d_shift_20_0_nonmem2rxOmega, {d_scanner_20_0_0_nonmem2rxOmega, d_scanner_20_0_1_nonmem2rxOmega
 , d_scanner_20_0_1_nonmem2rxOmega, d_scanner_20_0_1_nonmem2rxOmega}}
};

SB_trans_uint8 d_transition_20_nonmem2rxOmega[2] = {
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}}
};

SB_uint8 d_scanner_30_nonmem2rxOmega[11] = {
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_30_0_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_30_1_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_30_2_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_30_3_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_30_4_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{d_shift_18_6_nonmem2rxOmega, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_12_5_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{d_shift_18_7_nonmem2rxOmega, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_12_6_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_30_7_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_30_8_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{d_shift_18_10_nonmem2rxOmega, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{d_shift_18_11_nonmem2rxOmega, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}}
};

SB_trans_uint8 d_transition_30_nonmem2rxOmega[11] = {
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_18_6_1_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_18_7_1_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}}
};

SB_uint8 d_scanner_31_nonmem2rxOmega[14] = {
{NULL, {d_scanner_31_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_31_1_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{d_shift_31_2_nonmem2rxOmega, {d_scanner_31_2_0_nonmem2rxOmega, d_scanner_31_2_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{d_shift_31_2_nonmem2rxOmega, {d_scanner_31_3_0_nonmem2rxOmega, d_scanner_31_2_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{d_shift_31_4_nonmem2rxOmega, {d_scanner_31_1_0_nonmem2rxOmega, d_scanner_31_4_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{d_shift_31_4_nonmem2rxOmega, {d_scanner_31_5_0_nonmem2rxOmega, d_scanner_31_4_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_31_2_0_nonmem2rxOmega, d_scanner_31_2_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_31_7_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_31_8_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{d_shift_31_4_nonmem2rxOmega, {d_scanner_31_5_0_nonmem2rxOmega, d_scanner_31_4_1_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_31_10_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{d_shift_31_11_nonmem2rxOmega, {d_scanner_31_10_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{NULL, {d_scanner_31_12_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{d_shift_31_4_nonmem2rxOmega, {d_scanner_31_12_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}}
};

SB_trans_uint8 d_transition_31_nonmem2rxOmega[14] = {
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_31_2_0_nonmem2rxOmega, d_accepts_diff_31_2_1_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_31_3_0_nonmem2rxOmega, d_accepts_diff_31_2_1_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}}
};

SB_uint8 d_scanner_33_nonmem2rxOmega[3] = {
{NULL, {d_scanner_33_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{d_shift_31_2_nonmem2rxOmega, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{d_shift_31_2_nonmem2rxOmega, {d_scanner_33_2_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}}
};

SB_trans_uint8 d_transition_33_nonmem2rxOmega[3] = {
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}}
};

SB_uint8 d_scanner_45_nonmem2rxOmega[2] = {
{NULL, {d_scanner_45_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{d_shift_45_1_nonmem2rxOmega, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}}
};

SB_trans_uint8 d_transition_45_nonmem2rxOmega[2] = {
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}}
};

SB_uint8 d_scanner_46_nonmem2rxOmega[2] = {
{NULL, {d_scanner_18_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{d_shift_7_2_nonmem2rxOmega, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}}
};

SB_trans_uint8 d_transition_46_nonmem2rxOmega[2] = {
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}}
};

SB_uint8 d_scanner_49_nonmem2rxOmega[3] = {
{NULL, {d_scanner_49_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{d_shift_49_1_nonmem2rxOmega, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}},
{d_shift_7_3_nonmem2rxOmega, {d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega
 , d_scanner_0_0_0_nonmem2rxOmega, d_scanner_0_0_0_nonmem2rxOmega}}
};

SB_trans_uint8 d_transition_49_nonmem2rxOmega[3] = {
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}},
{{d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega
 , d_accepts_diff_0_0_0_nonmem2rxOmega, d_accepts_diff_0_0_0_nonmem2rxOmega}}
};

unsigned char d_goto_valid_0_nonmem2rxOmega[] = {
0xf2,0x3b,0x0,0x0,0x98,0x1,0x0,0x0};
D_Reduction * d_reductions_0_nonmem2rxOmega[] = {&d_reduction_6_nonmem2rxOmega};
unsigned char d_goto_valid_1_nonmem2rxOmega[] = {
0x0,0x0,0x0,0x30,0x0,0x0,0x0,0x0};
D_Reduction * d_reductions_1_nonmem2rxOmega[] = {&d_reduction_52_nonmem2rxOmega};
D_RightEpsilonHint d_right_epsilon_hints_1_nonmem2rxOmega[] = {{0, 17, &d_reduction_50_nonmem2rxOmega}};
D_Reduction * d_reductions_2_nonmem2rxOmega[] = {&d_reduction_8_nonmem2rxOmega};
D_Reduction * d_reductions_3_nonmem2rxOmega[] = {&d_reduction_8_nonmem2rxOmega};
D_Reduction * d_reductions_4_nonmem2rxOmega[] = {&d_reduction_11_nonmem2rxOmega};
D_Reduction * d_reductions_5_nonmem2rxOmega[] = {&d_reduction_11_nonmem2rxOmega};
unsigned char d_goto_valid_7_nonmem2rxOmega[] = {
0xc,0xc0,0xd9,0x86,0x20,0x0,0x40,0x1};
D_Reduction * d_reductions_7_nonmem2rxOmega[] = {&d_reduction_26_nonmem2rxOmega,&d_reduction_46_nonmem2rxOmega};
D_RightEpsilonHint d_right_epsilon_hints_7_nonmem2rxOmega[] = {{0, 24, &d_reduction_23_nonmem2rxOmega}};
D_Reduction * d_reductions_8_nonmem2rxOmega[] = {&d_reduction_18_nonmem2rxOmega};
unsigned char d_goto_valid_9_nonmem2rxOmega[] = {
0x0,0x0,0x0,0x0,0x20,0x0,0x0,0x0};
unsigned char d_goto_valid_10_nonmem2rxOmega[] = {
0x0,0x4,0x0,0x0,0x20,0x18,0x0,0x0};
D_Reduction * d_reductions_10_nonmem2rxOmega[] = {&d_reduction_18_nonmem2rxOmega};
D_Reduction * d_reductions_11_nonmem2rxOmega[] = {&d_reduction_10_nonmem2rxOmega};
unsigned char d_goto_valid_12_nonmem2rxOmega[] = {
0x0,0x4,0x0,0x0,0x0,0x18,0x0,0x0};
D_Reduction * d_reductions_12_nonmem2rxOmega[] = {&d_reduction_18_nonmem2rxOmega};
D_Reduction * d_reductions_13_nonmem2rxOmega[] = {&d_reduction_18_nonmem2rxOmega};
D_Reduction * d_reductions_14_nonmem2rxOmega[] = {&d_reduction_18_nonmem2rxOmega};
D_Reduction * d_reductions_15_nonmem2rxOmega[] = {&d_reduction_5_nonmem2rxOmega};
unsigned char d_goto_valid_17_nonmem2rxOmega[] = {
0x0,0x0,0x0,0x40,0x0,0x0,0x80,0x0};
D_Reduction * d_reductions_17_nonmem2rxOmega[] = {&d_reduction_50_nonmem2rxOmega};
unsigned char d_goto_valid_18_nonmem2rxOmega[] = {
0x0,0x0,0x10,0x7,0x0,0x0,0x7c,0x0};
D_Reduction * d_reductions_18_nonmem2rxOmega[] = {&d_reduction_46_nonmem2rxOmega};
D_Reduction * d_reductions_19_nonmem2rxOmega[] = {&d_reduction_45_nonmem2rxOmega};
unsigned char d_goto_valid_20_nonmem2rxOmega[] = {
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x2};
unsigned char d_goto_valid_21_nonmem2rxOmega[] = {
0x8,0xc0,0xd9,0x86,0x20,0x0,0x40,0x1};
D_Reduction * d_reductions_21_nonmem2rxOmega[] = {&d_reduction_1_nonmem2rxOmega,&d_reduction_26_nonmem2rxOmega,&d_reduction_46_nonmem2rxOmega};
D_RightEpsilonHint d_right_epsilon_hints_21_nonmem2rxOmega[] = {{0, 24, &d_reduction_23_nonmem2rxOmega}};
D_Reduction * d_reductions_22_nonmem2rxOmega[] = {&d_reduction_3_nonmem2rxOmega};
D_Reduction * d_reductions_23_nonmem2rxOmega[] = {&d_reduction_4_nonmem2rxOmega};
D_Reduction * d_reductions_24_nonmem2rxOmega[] = {&d_reduction_23_nonmem2rxOmega};
D_Reduction * d_reductions_25_nonmem2rxOmega[] = {&d_reduction_23_nonmem2rxOmega};
unsigned char d_goto_valid_26_nonmem2rxOmega[] = {
0x0,0x0,0x4,0x0,0x0,0x0,0x0,0x0};
D_Reduction * d_reductions_26_nonmem2rxOmega[] = {&d_reduction_31_nonmem2rxOmega};
D_RightEpsilonHint d_right_epsilon_hints_26_nonmem2rxOmega[] = {{1, 64, &d_reduction_27_nonmem2rxOmega}};
D_Reduction * d_reductions_27_nonmem2rxOmega[] = {&d_reduction_32_nonmem2rxOmega};
D_Reduction * d_reductions_28_nonmem2rxOmega[] = {&d_reduction_32_nonmem2rxOmega};
D_Reduction * d_reductions_29_nonmem2rxOmega[] = {&d_reduction_32_nonmem2rxOmega};
unsigned char d_goto_valid_30_nonmem2rxOmega[] = {
0x0,0x0,0x20,0x1,0x0,0x0,0x3c,0x0};
D_Reduction * d_reductions_30_nonmem2rxOmega[] = {&d_reduction_37_nonmem2rxOmega};
D_RightEpsilonHint d_right_epsilon_hints_30_nonmem2rxOmega[] = {{0, 50, &d_reduction_35_nonmem2rxOmega}};
unsigned char d_goto_valid_31_nonmem2rxOmega[] = {
0x0,0x0,0x0,0x8,0x7,0x0,0x0,0x1c};
D_Reduction * d_reductions_32_nonmem2rxOmega[] = {&d_reduction_25_nonmem2rxOmega};
unsigned char d_goto_valid_33_nonmem2rxOmega[] = {
0x0,0x0,0x0,0x0,0x1,0x0,0x0,0x4};
unsigned char d_goto_valid_34_nonmem2rxOmega[] = {
0x0,0x0,0x0,0x0,0x1,0x0,0x0,0x4};
D_Reduction * d_reductions_35_nonmem2rxOmega[] = {&d_reduction_14_nonmem2rxOmega};
D_Reduction * d_reductions_36_nonmem2rxOmega[] = {&d_reduction_14_nonmem2rxOmega};
D_Reduction * d_reductions_37_nonmem2rxOmega[] = {&d_reduction_17_nonmem2rxOmega};
D_Reduction * d_reductions_38_nonmem2rxOmega[] = {&d_reduction_16_nonmem2rxOmega};
D_Reduction * d_reductions_39_nonmem2rxOmega[] = {&d_reduction_53_nonmem2rxOmega};
D_Reduction * d_reductions_40_nonmem2rxOmega[] = {&d_reduction_51_nonmem2rxOmega};
D_Reduction * d_reductions_41_nonmem2rxOmega[] = {&d_reduction_40_nonmem2rxOmega};
D_Reduction * d_reductions_42_nonmem2rxOmega[] = {&d_reduction_40_nonmem2rxOmega};
D_Reduction * d_reductions_43_nonmem2rxOmega[] = {&d_reduction_40_nonmem2rxOmega};
D_Reduction * d_reductions_44_nonmem2rxOmega[] = {&d_reduction_40_nonmem2rxOmega};
unsigned char d_goto_valid_45_nonmem2rxOmega[] = {
0x0,0x0,0x0,0x0,0x40,0x0,0x0,0x0};
unsigned char d_goto_valid_46_nonmem2rxOmega[] = {
0x0,0x0,0x0,0x6,0x0,0x0,0x40,0x0};
D_Reduction * d_reductions_46_nonmem2rxOmega[] = {&d_reduction_46_nonmem2rxOmega};
D_Reduction * d_reductions_47_nonmem2rxOmega[] = {&d_reduction_54_nonmem2rxOmega};
D_Reduction * d_reductions_48_nonmem2rxOmega[] = {&d_reduction_2_nonmem2rxOmega};
unsigned char d_goto_valid_49_nonmem2rxOmega[] = {
0x0,0x0,0x2,0x80,0x0,0x20,0x0,0x1};
D_Reduction * d_reductions_49_nonmem2rxOmega[] = {&d_reduction_29_nonmem2rxOmega};
D_RightEpsilonHint d_right_epsilon_hints_49_nonmem2rxOmega[] = {{0, 64, &d_reduction_27_nonmem2rxOmega}};
D_Reduction * d_reductions_50_nonmem2rxOmega[] = {&d_reduction_35_nonmem2rxOmega};
D_Reduction * d_reductions_51_nonmem2rxOmega[] = {&d_reduction_36_nonmem2rxOmega};
D_Reduction * d_reductions_52_nonmem2rxOmega[] = {&d_reduction_55_nonmem2rxOmega};
D_Reduction * d_reductions_53_nonmem2rxOmega[] = {&d_reduction_56_nonmem2rxOmega};
D_Reduction * d_reductions_54_nonmem2rxOmega[] = {&d_reduction_57_nonmem2rxOmega};
D_Reduction * d_reductions_55_nonmem2rxOmega[] = {&d_reduction_44_nonmem2rxOmega};
D_Reduction * d_reductions_56_nonmem2rxOmega[] = {&d_reduction_47_nonmem2rxOmega};
D_Reduction * d_reductions_57_nonmem2rxOmega[] = {&d_reduction_47_nonmem2rxOmega};
D_Reduction * d_reductions_58_nonmem2rxOmega[] = {&d_reduction_47_nonmem2rxOmega};
unsigned char d_goto_valid_59_nonmem2rxOmega[] = {
0x0,0x0,0x0,0x0,0x40,0x0,0x0,0x0};
unsigned char d_goto_valid_60_nonmem2rxOmega[] = {
0x0,0x0,0x0,0x0,0x40,0x0,0x0,0x0};
D_Reduction * d_reductions_61_nonmem2rxOmega[] = {&d_reduction_38_nonmem2rxOmega};
unsigned char d_goto_valid_62_nonmem2rxOmega[] = {
0x0,0x0,0x0,0x0,0x40,0x0,0x0,0x0};
D_Reduction * d_reductions_63_nonmem2rxOmega[] = {&d_reduction_30_nonmem2rxOmega};
D_Reduction * d_reductions_64_nonmem2rxOmega[] = {&d_reduction_27_nonmem2rxOmega};
D_Reduction * d_reductions_65_nonmem2rxOmega[] = {&d_reduction_28_nonmem2rxOmega};
D_Reduction * d_reductions_66_nonmem2rxOmega[] = {&d_reduction_7_nonmem2rxOmega};
D_Reduction * d_reductions_67_nonmem2rxOmega[] = {&d_reduction_13_nonmem2rxOmega};
D_Reduction * d_reductions_68_nonmem2rxOmega[] = {&d_reduction_39_nonmem2rxOmega};
unsigned short d_gotos_nonmem2rxOmega[153] = {
7,17,18,8,9,10,11,12,13,34,14,15,16,48,50,62,
67,68,41,69,38,0,39,0,60,0,0,0,22,23,63,32,
61,0,3,4,0,0,5,6,24,25,26,40,0,27,28,35,
29,30,53,31,32,36,37,36,37,33,53,20,46,0,0,19,
47,31,32,0,0,0,0,0,0,0,0,0,0,0,0,0,
20,0,21,0,49,51,0,0,52,0,42,43,44,45,20,24,
25,26,0,65,27,28,0,29,30,0,31,32,0,0,0,0,
33,66,42,43,44,45,19,56,0,0,0,0,57,58,59,64,
0,0,0,0,0,0,0,20,0,21,21,0,0,0,0,0,
0,0,0,0,0,0,53,54,55};

D_ErrorRecoveryHint d_error_recovery_hints_0_nonmem2rxOmega[] = {{0, 5, ")"}};
D_ErrorRecoveryHint d_error_recovery_hints_7_nonmem2rxOmega[] = {{0, 22, ")"}};
D_ErrorRecoveryHint d_error_recovery_hints_9_nonmem2rxOmega[] = {{1, 5, ")"}};
D_ErrorRecoveryHint d_error_recovery_hints_10_nonmem2rxOmega[] = {{1, 9, ")"}};
D_ErrorRecoveryHint d_error_recovery_hints_18_nonmem2rxOmega[] = {{1, 22, ")"}};
D_ErrorRecoveryHint d_error_recovery_hints_26_nonmem2rxOmega[] = {{0, 18, ","}};
D_ErrorRecoveryHint d_error_recovery_hints_33_nonmem2rxOmega[] = {{2, 5, ")"}};
D_ErrorRecoveryHint d_error_recovery_hints_34_nonmem2rxOmega[] = {{2, 9, ")"}};
D_ErrorRecoveryHint d_error_recovery_hints_45_nonmem2rxOmega[] = {{2, 22, ")"}};
D_ErrorRecoveryHint d_error_recovery_hints_46_nonmem2rxOmega[] = {{2, 23, ")"}};
D_ErrorRecoveryHint d_error_recovery_hints_49_nonmem2rxOmega[] = {{1, 18, ","}};
D_ErrorRecoveryHint d_error_recovery_hints_59_nonmem2rxOmega[] = {{3, 5, ")"}};
D_ErrorRecoveryHint d_error_recovery_hints_60_nonmem2rxOmega[] = {{3, 9, ")"}};
D_ErrorRecoveryHint d_error_recovery_hints_61_nonmem2rxOmega[] = {{3, 22, ")"}};
D_ErrorRecoveryHint d_error_recovery_hints_62_nonmem2rxOmega[] = {{3, 23, ")"}};
D_ErrorRecoveryHint d_error_recovery_hints_63_nonmem2rxOmega[] = {{2, 18, ","}};
D_ErrorRecoveryHint d_error_recovery_hints_66_nonmem2rxOmega[] = {{4, 5, ")"}};
D_ErrorRecoveryHint d_error_recovery_hints_67_nonmem2rxOmega[] = {{4, 9, ")"}};
D_ErrorRecoveryHint d_error_recovery_hints_68_nonmem2rxOmega[] = {{4, 23, ")"}};

D_State d_states_nonmem2rxOmega[] = {
{d_goto_valid_0_nonmem2rxOmega, 1, {1, d_reductions_0_nonmem2rxOmega}, {0, NULL}, {1, d_error_recovery_hints_0_nonmem2rxOmega}, 1, NULL, (void*)d_scanner_0_nonmem2rxOmega, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_0_nonmem2rxOmega, d_accepts_diff_0_nonmem2rxOmega, -1},
{d_goto_valid_1_nonmem2rxOmega, 27, {1, d_reductions_1_nonmem2rxOmega}, {1, d_right_epsilon_hints_1_nonmem2rxOmega}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_2_nonmem2rxOmega}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_3_nonmem2rxOmega}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_4_nonmem2rxOmega}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_5_nonmem2rxOmega}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {0, NULL}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 1, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_7_nonmem2rxOmega, -26, {2, d_reductions_7_nonmem2rxOmega}, {1, d_right_epsilon_hints_7_nonmem2rxOmega}, {1, d_error_recovery_hints_7_nonmem2rxOmega}, 1, NULL, (void*)d_scanner_7_nonmem2rxOmega, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_7_nonmem2rxOmega, d_accepts_diff_7_nonmem2rxOmega, -1},
{NULL, -2147483647, {1, d_reductions_8_nonmem2rxOmega}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_9_nonmem2rxOmega, 28, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_9_nonmem2rxOmega}, 1, NULL, (void*)d_scanner_9_nonmem2rxOmega, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_9_nonmem2rxOmega, d_accepts_diff_9_nonmem2rxOmega, -1},
{d_goto_valid_10_nonmem2rxOmega, -10, {1, d_reductions_10_nonmem2rxOmega}, {0, NULL}, {1, d_error_recovery_hints_10_nonmem2rxOmega}, 1, NULL, (void*)d_scanner_10_nonmem2rxOmega, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_10_nonmem2rxOmega, d_accepts_diff_10_nonmem2rxOmega, -1},
{NULL, -2147483647, {1, d_reductions_11_nonmem2rxOmega}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_12_nonmem2rxOmega, -12, {1, d_reductions_12_nonmem2rxOmega}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_12_nonmem2rxOmega, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_12_nonmem2rxOmega, d_accepts_diff_12_nonmem2rxOmega, -1},
{NULL, -2147483647, {1, d_reductions_13_nonmem2rxOmega}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_14_nonmem2rxOmega}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_15_nonmem2rxOmega}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {0, NULL}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 1, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_17_nonmem2rxOmega, 12, {1, d_reductions_17_nonmem2rxOmega}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_17_nonmem2rxOmega, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_17_nonmem2rxOmega, d_accepts_diff_17_nonmem2rxOmega, -1},
{d_goto_valid_18_nonmem2rxOmega, -40, {1, d_reductions_18_nonmem2rxOmega}, {0, NULL}, {1, d_error_recovery_hints_18_nonmem2rxOmega}, 1, NULL, (void*)d_scanner_18_nonmem2rxOmega, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_18_nonmem2rxOmega, d_accepts_diff_18_nonmem2rxOmega, -1},
{NULL, -2147483647, {1, d_reductions_19_nonmem2rxOmega}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_20_nonmem2rxOmega, 44, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_20_nonmem2rxOmega, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_20_nonmem2rxOmega, d_accepts_diff_20_nonmem2rxOmega, -1},
{d_goto_valid_21_nonmem2rxOmega, -81, {3, d_reductions_21_nonmem2rxOmega}, {1, d_right_epsilon_hints_21_nonmem2rxOmega}, {1, d_error_recovery_hints_7_nonmem2rxOmega}, 1, NULL, (void*)d_scanner_7_nonmem2rxOmega, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_7_nonmem2rxOmega, d_accepts_diff_7_nonmem2rxOmega, -1},
{NULL, -2147483647, {1, d_reductions_22_nonmem2rxOmega}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_23_nonmem2rxOmega}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_24_nonmem2rxOmega}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_25_nonmem2rxOmega}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_26_nonmem2rxOmega, 4, {1, d_reductions_26_nonmem2rxOmega}, {1, d_right_epsilon_hints_26_nonmem2rxOmega}, {1, d_error_recovery_hints_26_nonmem2rxOmega}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_27_nonmem2rxOmega}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_28_nonmem2rxOmega}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_29_nonmem2rxOmega}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_30_nonmem2rxOmega, -64, {1, d_reductions_30_nonmem2rxOmega}, {1, d_right_epsilon_hints_30_nonmem2rxOmega}, {0, NULL}, 1, NULL, (void*)d_scanner_30_nonmem2rxOmega, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_30_nonmem2rxOmega, d_accepts_diff_30_nonmem2rxOmega, -1},
{d_goto_valid_31_nonmem2rxOmega, -92, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_31_nonmem2rxOmega, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_31_nonmem2rxOmega, d_accepts_diff_31_nonmem2rxOmega, -1},
{NULL, -2147483647, {1, d_reductions_32_nonmem2rxOmega}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_33_nonmem2rxOmega, 8, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_33_nonmem2rxOmega}, 1, NULL, (void*)d_scanner_33_nonmem2rxOmega, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_33_nonmem2rxOmega, d_accepts_diff_33_nonmem2rxOmega, -1},
{d_goto_valid_34_nonmem2rxOmega, 0, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_34_nonmem2rxOmega}, 1, NULL, (void*)d_scanner_33_nonmem2rxOmega, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_33_nonmem2rxOmega, d_accepts_diff_33_nonmem2rxOmega, -1},
{NULL, -2147483647, {1, d_reductions_35_nonmem2rxOmega}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_36_nonmem2rxOmega}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_37_nonmem2rxOmega}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_38_nonmem2rxOmega}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_39_nonmem2rxOmega}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_40_nonmem2rxOmega}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_41_nonmem2rxOmega}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_42_nonmem2rxOmega}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_43_nonmem2rxOmega}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_44_nonmem2rxOmega}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_45_nonmem2rxOmega, 23, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_45_nonmem2rxOmega}, 1, NULL, (void*)d_scanner_45_nonmem2rxOmega, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_45_nonmem2rxOmega, d_accepts_diff_45_nonmem2rxOmega, -1},
{d_goto_valid_46_nonmem2rxOmega, -5, {1, d_reductions_46_nonmem2rxOmega}, {0, NULL}, {1, d_error_recovery_hints_46_nonmem2rxOmega}, 1, NULL, (void*)d_scanner_46_nonmem2rxOmega, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_46_nonmem2rxOmega, d_accepts_diff_46_nonmem2rxOmega, -1},
{NULL, -2147483647, {1, d_reductions_47_nonmem2rxOmega}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_48_nonmem2rxOmega}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_49_nonmem2rxOmega, -82, {1, d_reductions_49_nonmem2rxOmega}, {1, d_right_epsilon_hints_49_nonmem2rxOmega}, {1, d_error_recovery_hints_49_nonmem2rxOmega}, 1, NULL, (void*)d_scanner_49_nonmem2rxOmega, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_49_nonmem2rxOmega, d_accepts_diff_49_nonmem2rxOmega, -1},
{NULL, -2147483647, {1, d_reductions_50_nonmem2rxOmega}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_51_nonmem2rxOmega}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_52_nonmem2rxOmega}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_53_nonmem2rxOmega}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_54_nonmem2rxOmega}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_55_nonmem2rxOmega}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_56_nonmem2rxOmega}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_57_nonmem2rxOmega}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_58_nonmem2rxOmega}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_59_nonmem2rxOmega, 22, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_59_nonmem2rxOmega}, 1, NULL, (void*)d_scanner_45_nonmem2rxOmega, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_45_nonmem2rxOmega, d_accepts_diff_45_nonmem2rxOmega, -1},
{d_goto_valid_60_nonmem2rxOmega, 21, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_60_nonmem2rxOmega}, 1, NULL, (void*)d_scanner_45_nonmem2rxOmega, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_45_nonmem2rxOmega, d_accepts_diff_45_nonmem2rxOmega, -1},
{NULL, -2147483647, {1, d_reductions_61_nonmem2rxOmega}, {0, NULL}, {1, d_error_recovery_hints_61_nonmem2rxOmega}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_62_nonmem2rxOmega, 19, {0, NULL}, {0, NULL}, {1, d_error_recovery_hints_62_nonmem2rxOmega}, 1, NULL, (void*)d_scanner_45_nonmem2rxOmega, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_45_nonmem2rxOmega, d_accepts_diff_45_nonmem2rxOmega, -1},
{NULL, -2147483647, {1, d_reductions_63_nonmem2rxOmega}, {0, NULL}, {1, d_error_recovery_hints_63_nonmem2rxOmega}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_64_nonmem2rxOmega}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_65_nonmem2rxOmega}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_66_nonmem2rxOmega}, {0, NULL}, {1, d_error_recovery_hints_66_nonmem2rxOmega}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_67_nonmem2rxOmega}, {0, NULL}, {1, d_error_recovery_hints_67_nonmem2rxOmega}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_68_nonmem2rxOmega}, {0, NULL}, {1, d_error_recovery_hints_68_nonmem2rxOmega}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1}
};

D_Symbol d_symbols_nonmem2rxOmega[] = {
{D_SYMBOL_EBNF, "0 Start", 7, -1},
{D_SYMBOL_NTERM, "statement_list", 14, -1},
{D_SYMBOL_INTERNAL, "statement_list__4", 17, -1},
{D_SYMBOL_EBNF, "statement_list__3", 17, -1},
{D_SYMBOL_INTERNAL, "statement_list__2", 17, -1},
{D_SYMBOL_NTERM, "diagonal", 8, -1},
{D_SYMBOL_EBNF, "diagonal__6", 11, -1},
{D_SYMBOL_NTERM, "block", 5, -1},
{D_SYMBOL_EBNF, "block__8", 8, -1},
{D_SYMBOL_NTERM, "blockn", 6, -1},
{D_SYMBOL_NTERM, "same", 4, -1},
{D_SYMBOL_NTERM, "blocknsame", 10, -1},
{D_SYMBOL_NTERM, "blocksame", 9, -1},
{D_SYMBOL_NTERM, "first", 5, -1},
{D_SYMBOL_NTERM, "statement", 9, -1},
{D_SYMBOL_INTERNAL, "statement__15", 13, -1},
{D_SYMBOL_NTERM, "omega_statement", 15, -1},
{D_SYMBOL_INTERNAL, "omega_statement__18", 19, -1},
{D_SYMBOL_INTERNAL, "omega_statement__17", 19, -1},
{D_SYMBOL_NTERM, "omega", 5, -1},
{D_SYMBOL_NTERM, "omega0", 6, -1},
{D_SYMBOL_INTERNAL, "omega0__21", 10, -1},
{D_SYMBOL_NTERM, "omega1", 6, -1},
{D_SYMBOL_NTERM, "omega2", 6, -1},
{D_SYMBOL_NTERM, "fixed", 5, -1},
{D_SYMBOL_NTERM, "ini_constant", 12, -1},
{D_SYMBOL_INTERNAL, "ini_constant__26", 16, -1},
{D_SYMBOL_NTERM, "constant", 8, -1},
{D_SYMBOL_NTERM, "whitespace", 10, 1},
{D_SYMBOL_INTERNAL, "whitespace__30", 14, -1},
{D_SYMBOL_EBNF, "whitespace__29", 14, -1},
{D_SYMBOL_NTERM, "singleLineComment", 17, -1},
{D_SYMBOL_NTERM, "decimalint", 10, -1},
{D_SYMBOL_NTERM, "float1", 6, -1},
{D_SYMBOL_NTERM, "float2", 6, -1},
{D_SYMBOL_STRING, "diagonal", 8, -1},
{D_SYMBOL_STRING, "DIAGONAL", 8, -1},
{D_SYMBOL_STRING, "(", 1, -1},
{D_SYMBOL_STRING, ")", 1, -1},
{D_SYMBOL_STRING, "block", 5, -1},
{D_SYMBOL_STRING, "BLOCK", 5, -1},
{D_SYMBOL_STRING, "(", 1, -1},
{D_SYMBOL_STRING, ")", 1, -1},
{D_SYMBOL_STRING, "SAME", 4, -1},
{D_SYMBOL_STRING, "same", 4, -1},
{D_SYMBOL_STRING, ",", 1, -1},
{D_SYMBOL_STRING, "(", 1, -1},
{D_SYMBOL_STRING, ")", 1, -1},
{D_SYMBOL_STRING, "(", 1, -1},
{D_SYMBOL_STRING, ")", 1, -1},
{D_SYMBOL_STRING, "fixed", 5, -1},
{D_SYMBOL_STRING, "FIXED", 5, -1},
{D_SYMBOL_STRING, "FIX", 3, -1},
{D_SYMBOL_STRING, "fix", 3, -1},
{D_SYMBOL_STRING, "-", 1, -1},
{D_SYMBOL_REGEX, "[ \\t\\r\\n]+", 13, -1},
{D_SYMBOL_STRING, ";", 1, -1},
{D_SYMBOL_REGEX, "[^\\n]*", 7, -1},
{D_SYMBOL_REGEX, "0|([1-9][0-9]*)", 15, -1},
{D_SYMBOL_REGEX, "([0-9]+.[0-9]*|[0-9]*.[0-9]+)([eE][\\\\-\\\\+]?[0-9]+)?", 55, -1},
{D_SYMBOL_REGEX, "[0-9]+[eE][\\\\-\\\\+]?[0-9]+", 29, -1},
};

D_ParserTables parser_tables_nonmem2rxOmega = {
69, d_states_nonmem2rxOmega, d_gotos_nonmem2rxOmega, 1, 61, d_symbols_nonmem2rxOmega, NULL, 0, NULL, 0};
