#include <R.h>
#include <Rinternals.h>
#define printf Rprintf

/*
  Generated by Make DParser Version 1.31.4ab9d43046e5d22ffb365ec5f5184a7cfee09b30
  Available at https://github.com/jplevyak/dparser
*/

#line 7 "/home/matt/src/nonmem2rx/src/records.g.d_parser.c"
#include "dparse.h"

D_Reduction d_reduction_0_nonmem2rxRecords = {1, 0, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_1_nonmem2rxRecords = {1, 1, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_2_nonmem2rxRecords = {2, 2, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_3_nonmem2rxRecords = {1, 2, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_4_nonmem2rxRecords = {1, 3, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_5_nonmem2rxRecords = {1, 4, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_7_nonmem2rxRecords = {3, 5, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_8_nonmem2rxRecords = {2, 6, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_9_nonmem2rxRecords = {1, 7, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_10_nonmem2rxRecords = {2, 8, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_11_nonmem2rxRecords = {0, 8, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_12_nonmem2rxRecords = {1, 9, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Shift d_shift_0_nonmem2rxRecords = {10, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_1_nonmem2rxRecords = {11, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_2_nonmem2rxRecords = {12, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_3_nonmem2rxRecords = {13, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_4_nonmem2rxRecords = {14, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_5_nonmem2rxRecords = {15, 0, 0, 0, 0, 0, NULL};

D_Shift * d_accepts_diff_0_0_nonmem2rxRecords[] = {0};
D_Shift ** d_accepts_diff_0_nonmem2rxRecords[] = {
d_accepts_diff_0_0_nonmem2rxRecords
};

unsigned char d_scanner_0_0_0_nonmem2rxRecords[SCANNER_BLOCK_SIZE] = {
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
};

unsigned char d_accepts_diff_0_0_0_nonmem2rxRecords[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_0_0_1_nonmem2rxRecords[SCANNER_BLOCK_SIZE] = {
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
};

unsigned char d_scanner_0_1_0_nonmem2rxRecords[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_0_1_nonmem2rxRecords[] = {&d_shift_3_nonmem2rxRecords,NULL};

D_Shift * d_shift_0_2_nonmem2rxRecords[] = {&d_shift_0_nonmem2rxRecords,NULL};

D_Shift * d_accepts_diff_2_0_nonmem2rxRecords[] = {0};
D_Shift ** d_accepts_diff_2_nonmem2rxRecords[] = {
d_accepts_diff_2_0_nonmem2rxRecords
};

unsigned char d_scanner_2_0_1_nonmem2rxRecords[SCANNER_BLOCK_SIZE] = {
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_2_1_nonmem2rxRecords[] = {&d_shift_1_nonmem2rxRecords,NULL};

D_Shift * d_accepts_diff_3_0_nonmem2rxRecords[] = {0};
D_Shift ** d_accepts_diff_3_nonmem2rxRecords[] = {
d_accepts_diff_3_0_nonmem2rxRecords
};

unsigned char d_scanner_3_0_0_nonmem2rxRecords[SCANNER_BLOCK_SIZE] = {
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
};

D_Shift * d_shift_3_0_nonmem2rxRecords[] = {&d_shift_2_nonmem2rxRecords,NULL};

D_Shift * d_accepts_diff_11_0_nonmem2rxRecords[] = {0};
D_Shift ** d_accepts_diff_11_nonmem2rxRecords[] = {
d_accepts_diff_11_0_nonmem2rxRecords
};

unsigned char d_scanner_11_0_0_nonmem2rxRecords[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_11_1_nonmem2rxRecords[] = {&d_shift_5_nonmem2rxRecords,NULL};

SB_uint8 d_scanner_0_nonmem2rxRecords[3] = {
{NULL, {d_scanner_0_0_0_nonmem2rxRecords, d_scanner_0_0_1_nonmem2rxRecords
 , d_scanner_0_0_1_nonmem2rxRecords, d_scanner_0_0_1_nonmem2rxRecords}},
{d_shift_0_1_nonmem2rxRecords, {d_scanner_0_1_0_nonmem2rxRecords, d_scanner_0_1_0_nonmem2rxRecords
 , d_scanner_0_1_0_nonmem2rxRecords, d_scanner_0_1_0_nonmem2rxRecords}},
{d_shift_0_2_nonmem2rxRecords, {d_scanner_0_1_0_nonmem2rxRecords, d_scanner_0_1_0_nonmem2rxRecords
 , d_scanner_0_1_0_nonmem2rxRecords, d_scanner_0_1_0_nonmem2rxRecords}}
};

SB_trans_uint8 d_transition_0_nonmem2rxRecords[3] = {
{{d_accepts_diff_0_0_0_nonmem2rxRecords, d_accepts_diff_0_0_0_nonmem2rxRecords
 , d_accepts_diff_0_0_0_nonmem2rxRecords, d_accepts_diff_0_0_0_nonmem2rxRecords}},
{{d_accepts_diff_0_0_0_nonmem2rxRecords, d_accepts_diff_0_0_0_nonmem2rxRecords
 , d_accepts_diff_0_0_0_nonmem2rxRecords, d_accepts_diff_0_0_0_nonmem2rxRecords}},
{{d_accepts_diff_0_0_0_nonmem2rxRecords, d_accepts_diff_0_0_0_nonmem2rxRecords
 , d_accepts_diff_0_0_0_nonmem2rxRecords, d_accepts_diff_0_0_0_nonmem2rxRecords}}
};

SB_uint8 d_scanner_2_nonmem2rxRecords[2] = {
{NULL, {d_scanner_0_1_0_nonmem2rxRecords, d_scanner_2_0_1_nonmem2rxRecords
 , d_scanner_0_1_0_nonmem2rxRecords, d_scanner_0_1_0_nonmem2rxRecords}},
{d_shift_2_1_nonmem2rxRecords, {d_scanner_0_1_0_nonmem2rxRecords, d_scanner_2_0_1_nonmem2rxRecords
 , d_scanner_0_1_0_nonmem2rxRecords, d_scanner_0_1_0_nonmem2rxRecords}}
};

SB_trans_uint8 d_transition_2_nonmem2rxRecords[2] = {
{{d_accepts_diff_0_0_0_nonmem2rxRecords, d_accepts_diff_0_0_0_nonmem2rxRecords
 , d_accepts_diff_0_0_0_nonmem2rxRecords, d_accepts_diff_0_0_0_nonmem2rxRecords}},
{{d_accepts_diff_0_0_0_nonmem2rxRecords, d_accepts_diff_0_0_0_nonmem2rxRecords
 , d_accepts_diff_0_0_0_nonmem2rxRecords, d_accepts_diff_0_0_0_nonmem2rxRecords}}
};

SB_uint8 d_scanner_3_nonmem2rxRecords[2] = {
{d_shift_3_0_nonmem2rxRecords, {d_scanner_3_0_0_nonmem2rxRecords, d_scanner_0_0_1_nonmem2rxRecords
 , d_scanner_0_0_1_nonmem2rxRecords, d_scanner_0_0_1_nonmem2rxRecords}},
{d_shift_3_0_nonmem2rxRecords, {d_scanner_3_0_0_nonmem2rxRecords, d_scanner_0_0_1_nonmem2rxRecords
 , d_scanner_0_0_1_nonmem2rxRecords, d_scanner_0_0_1_nonmem2rxRecords}}
};

SB_trans_uint8 d_transition_3_nonmem2rxRecords[2] = {
{{d_accepts_diff_0_0_0_nonmem2rxRecords, d_accepts_diff_0_0_0_nonmem2rxRecords
 , d_accepts_diff_0_0_0_nonmem2rxRecords, d_accepts_diff_0_0_0_nonmem2rxRecords}},
{{d_accepts_diff_0_0_0_nonmem2rxRecords, d_accepts_diff_0_0_0_nonmem2rxRecords
 , d_accepts_diff_0_0_0_nonmem2rxRecords, d_accepts_diff_0_0_0_nonmem2rxRecords}}
};

SB_uint8 d_scanner_11_nonmem2rxRecords[2] = {
{NULL, {d_scanner_11_0_0_nonmem2rxRecords, d_scanner_0_1_0_nonmem2rxRecords
 , d_scanner_0_1_0_nonmem2rxRecords, d_scanner_0_1_0_nonmem2rxRecords}},
{d_shift_11_1_nonmem2rxRecords, {d_scanner_11_0_0_nonmem2rxRecords, d_scanner_0_1_0_nonmem2rxRecords
 , d_scanner_0_1_0_nonmem2rxRecords, d_scanner_0_1_0_nonmem2rxRecords}}
};

SB_trans_uint8 d_transition_11_nonmem2rxRecords[2] = {
{{d_accepts_diff_0_0_0_nonmem2rxRecords, d_accepts_diff_0_0_0_nonmem2rxRecords
 , d_accepts_diff_0_0_0_nonmem2rxRecords, d_accepts_diff_0_0_0_nonmem2rxRecords}},
{{d_accepts_diff_0_0_0_nonmem2rxRecords, d_accepts_diff_0_0_0_nonmem2rxRecords
 , d_accepts_diff_0_0_0_nonmem2rxRecords, d_accepts_diff_0_0_0_nonmem2rxRecords}}
};

unsigned char d_goto_valid_0_nonmem2rxRecords[] = {
0x7e,0x24};
unsigned char d_goto_valid_1_nonmem2rxRecords[] = {
0x80,0x1};
D_Reduction * d_reductions_1_nonmem2rxRecords[] = {&d_reduction_11_nonmem2rxRecords};
D_RightEpsilonHint d_right_epsilon_hints_1_nonmem2rxRecords[] = {{0, 11, &d_reduction_9_nonmem2rxRecords}};
unsigned char d_goto_valid_2_nonmem2rxRecords[] = {
0x0,0x8};
unsigned char d_goto_valid_3_nonmem2rxRecords[] = {
0x0,0x10};
unsigned char d_goto_valid_5_nonmem2rxRecords[] = {
0x78,0x24};
D_Reduction * d_reductions_5_nonmem2rxRecords[] = {&d_reduction_1_nonmem2rxRecords};
D_Reduction * d_reductions_6_nonmem2rxRecords[] = {&d_reduction_3_nonmem2rxRecords};
D_Reduction * d_reductions_7_nonmem2rxRecords[] = {&d_reduction_4_nonmem2rxRecords};
D_Reduction * d_reductions_8_nonmem2rxRecords[] = {&d_reduction_5_nonmem2rxRecords};
D_Reduction * d_reductions_9_nonmem2rxRecords[] = {&d_reduction_5_nonmem2rxRecords};
unsigned char d_goto_valid_11_nonmem2rxRecords[] = {
0x0,0x82};
D_Reduction * d_reductions_11_nonmem2rxRecords[] = {&d_reduction_9_nonmem2rxRecords};
unsigned char d_goto_valid_12_nonmem2rxRecords[] = {
0x0,0x10};
D_Reduction * d_reductions_13_nonmem2rxRecords[] = {&d_reduction_8_nonmem2rxRecords};
D_Reduction * d_reductions_14_nonmem2rxRecords[] = {&d_reduction_2_nonmem2rxRecords};
D_Reduction * d_reductions_15_nonmem2rxRecords[] = {&d_reduction_12_nonmem2rxRecords};
D_Reduction * d_reductions_16_nonmem2rxRecords[] = {&d_reduction_10_nonmem2rxRecords};
D_Reduction * d_reductions_17_nonmem2rxRecords[] = {&d_reduction_7_nonmem2rxRecords};
unsigned short d_gotos_nonmem2rxRecords[24] = {
5,6,7,8,9,10,11,12,13,3,14,17,4,15,8,9,
10,16,18,0,3,0,0,4};


D_State d_states_nonmem2rxRecords[] = {
{d_goto_valid_0_nonmem2rxRecords, 1, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_0_nonmem2rxRecords, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_0_nonmem2rxRecords, d_accepts_diff_0_nonmem2rxRecords, -1},
{d_goto_valid_1_nonmem2rxRecords, 1, {1, d_reductions_1_nonmem2rxRecords}, {1, d_right_epsilon_hints_1_nonmem2rxRecords}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_2_nonmem2rxRecords, 3, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_2_nonmem2rxRecords, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_2_nonmem2rxRecords, d_accepts_diff_2_nonmem2rxRecords, -1},
{d_goto_valid_3_nonmem2rxRecords, 2, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_3_nonmem2rxRecords, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_3_nonmem2rxRecords, d_accepts_diff_3_nonmem2rxRecords, -1},
{NULL, -2147483647, {0, NULL}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 1, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_5_nonmem2rxRecords, -10, {1, d_reductions_5_nonmem2rxRecords}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_0_nonmem2rxRecords, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_0_nonmem2rxRecords, d_accepts_diff_0_nonmem2rxRecords, -1},
{NULL, -2147483647, {1, d_reductions_6_nonmem2rxRecords}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_7_nonmem2rxRecords}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_8_nonmem2rxRecords}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_9_nonmem2rxRecords}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {0, NULL}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 1, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_11_nonmem2rxRecords, -2, {1, d_reductions_11_nonmem2rxRecords}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_11_nonmem2rxRecords, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_11_nonmem2rxRecords, d_accepts_diff_11_nonmem2rxRecords, -1},
{d_goto_valid_12_nonmem2rxRecords, -6, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_3_nonmem2rxRecords, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_3_nonmem2rxRecords, d_accepts_diff_3_nonmem2rxRecords, -1},
{NULL, -2147483647, {1, d_reductions_13_nonmem2rxRecords}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_14_nonmem2rxRecords}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_15_nonmem2rxRecords}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_16_nonmem2rxRecords}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_17_nonmem2rxRecords}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1}
};

D_Symbol d_symbols_nonmem2rxRecords[] = {
{D_SYMBOL_EBNF, "0 Start", 7, -1},
{D_SYMBOL_NTERM, "statement_list", 14, -1},
{D_SYMBOL_INTERNAL, "statement_list__3", 17, -1},
{D_SYMBOL_EBNF, "statement_list__2", 17, -1},
{D_SYMBOL_NTERM, "statement", 9, -1},
{D_SYMBOL_NTERM, "singleLineRecord", 16, -1},
{D_SYMBOL_NTERM, "singleLineNoRecord", 18, -1},
{D_SYMBOL_NTERM, "whitespace", 10, 1},
{D_SYMBOL_INTERNAL, "whitespace__9", 13, -1},
{D_SYMBOL_EBNF, "whitespace__8", 13, -1},
{D_SYMBOL_REGEX, "[$]", 3, -1},
{D_SYMBOL_REGEX, "[A-Za-z]+", 9, -1},
{D_SYMBOL_REGEX, "[^\\n]*", 7, -1},
{D_SYMBOL_REGEX, "[^$]", 4, -1},
{D_SYMBOL_REGEX, "[^\\n]*", 7, -1},
{D_SYMBOL_REGEX, "[ \\t\\r\\n]+", 13, -1},
};

D_ParserTables parser_tables_nonmem2rxRecords = {
18, d_states_nonmem2rxRecords, d_gotos_nonmem2rxRecords, 1, 16, d_symbols_nonmem2rxRecords, NULL, 0, NULL, 0};
