#include <R.h>
#include <Rinternals.h>
#define printf Rprintf

/*
  Generated by Make DParser Version 1.31.4ab9d43046e5d22ffb365ec5f5184a7cfee09b30
  Available at https://github.com/jplevyak/dparser
*/

#line 7 "/home/matt/src/nonmem2rx/src/records.g.d_parser.c"
#include "dparse.h"

D_Reduction d_reduction_0_nonmem2rxRecords = {1, 0, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_1_nonmem2rxRecords = {1, 1, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_2_nonmem2rxRecords = {2, 2, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_3_nonmem2rxRecords = {1, 2, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_4_nonmem2rxRecords = {1, 3, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_5_nonmem2rxRecords = {1, 4, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_7_nonmem2rxRecords = {2, 5, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_8_nonmem2rxRecords = {1, 6, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_9_nonmem2rxRecords = {0, 6, NULL, NULL, 0, 0, 0, 0, -1, 0, NULL};
D_Reduction d_reduction_10_nonmem2rxRecords = {5, 7, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_11_nonmem2rxRecords = {1, 8, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Reduction d_reduction_12_nonmem2rxRecords = {2, 9, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_0_nonmem2rxRecords = {10, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_1_nonmem2rxRecords = {11, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_2_nonmem2rxRecords = {12, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_3_nonmem2rxRecords = {13, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_4_nonmem2rxRecords = {14, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_5_nonmem2rxRecords = {15, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_6_nonmem2rxRecords = {16, 0, 0, 0, 0, 0, NULL};
D_Shift d_shift_7_nonmem2rxRecords = {17, 0, 0, 0, 0, 0, NULL};

D_Shift * d_accepts_diff_0_0_nonmem2rxRecords[] = {0};
D_Shift * d_accepts_diff_0_1_nonmem2rxRecords[] = {&d_shift_0_nonmem2rxRecords,0};
D_Shift ** d_accepts_diff_0_nonmem2rxRecords[] = {
d_accepts_diff_0_0_nonmem2rxRecords,
d_accepts_diff_0_1_nonmem2rxRecords
};

unsigned char d_scanner_0_0_0_nonmem2rxRecords[SCANNER_BLOCK_SIZE] = {
0, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 3, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
3, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
};

unsigned char d_accepts_diff_0_0_0_nonmem2rxRecords[SCANNER_BLOCK_SIZE] = {
0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
};

unsigned char d_scanner_0_0_1_nonmem2rxRecords[SCANNER_BLOCK_SIZE] = {
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
};

unsigned char d_accepts_diff_0_0_1_nonmem2rxRecords[SCANNER_BLOCK_SIZE] = {
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
};

D_Shift * d_shift_0_0_nonmem2rxRecords[] = {&d_shift_0_nonmem2rxRecords,NULL};

unsigned char d_scanner_0_1_0_nonmem2rxRecords[SCANNER_BLOCK_SIZE] = {
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
};

unsigned char d_accepts_diff_0_1_0_nonmem2rxRecords[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_0_1_nonmem2rxRecords[] = {&d_shift_5_nonmem2rxRecords,NULL};

unsigned char d_scanner_0_2_0_nonmem2rxRecords[SCANNER_BLOCK_SIZE] = {
0, 2, 2, 2, 2, 2, 2, 2, 2, 3, 0, 2, 2, 3, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
};

unsigned char d_accepts_diff_0_2_0_nonmem2rxRecords[SCANNER_BLOCK_SIZE] = {
0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
};

D_Shift * d_shift_0_2_nonmem2rxRecords[] = {&d_shift_0_nonmem2rxRecords,&d_shift_5_nonmem2rxRecords,NULL};

D_Shift * d_accepts_diff_1_0_nonmem2rxRecords[] = {0};
D_Shift ** d_accepts_diff_1_nonmem2rxRecords[] = {
d_accepts_diff_1_0_nonmem2rxRecords
};

unsigned char d_scanner_1_0_0_nonmem2rxRecords[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

unsigned char d_scanner_1_0_1_nonmem2rxRecords[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_1_1_nonmem2rxRecords[] = {&d_shift_1_nonmem2rxRecords,NULL};

D_Shift * d_accepts_diff_8_0_nonmem2rxRecords[] = {0};
D_Shift ** d_accepts_diff_8_nonmem2rxRecords[] = {
d_accepts_diff_8_0_nonmem2rxRecords
};

unsigned char d_scanner_8_0_0_nonmem2rxRecords[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 
};

D_Shift * d_shift_8_1_nonmem2rxRecords[] = {&d_shift_6_nonmem2rxRecords,NULL};

D_Shift * d_accepts_diff_10_0_nonmem2rxRecords[] = {0};
D_Shift ** d_accepts_diff_10_nonmem2rxRecords[] = {
d_accepts_diff_10_0_nonmem2rxRecords
};

unsigned char d_scanner_10_0_0_nonmem2rxRecords[SCANNER_BLOCK_SIZE] = {
0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
};

D_Shift * d_accepts_diff_12_0_nonmem2rxRecords[] = {0};
D_Shift ** d_accepts_diff_12_nonmem2rxRecords[] = {
d_accepts_diff_12_0_nonmem2rxRecords
};

D_Shift * d_shift_12_0_nonmem2rxRecords[] = {&d_shift_7_nonmem2rxRecords,NULL};

D_Shift * d_accepts_diff_15_0_nonmem2rxRecords[] = {0};
D_Shift ** d_accepts_diff_15_nonmem2rxRecords[] = {
d_accepts_diff_15_0_nonmem2rxRecords
};

unsigned char d_scanner_15_0_1_nonmem2rxRecords[SCANNER_BLOCK_SIZE] = {
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 
};

D_Shift * d_shift_15_1_nonmem2rxRecords[] = {&d_shift_3_nonmem2rxRecords,NULL};

D_Shift * d_accepts_diff_17_0_nonmem2rxRecords[] = {0};
D_Shift ** d_accepts_diff_17_nonmem2rxRecords[] = {
d_accepts_diff_17_0_nonmem2rxRecords
};

unsigned char d_scanner_17_0_0_nonmem2rxRecords[SCANNER_BLOCK_SIZE] = {
0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 
};

D_Shift * d_shift_17_0_nonmem2rxRecords[] = {&d_shift_4_nonmem2rxRecords,NULL};

SB_uint8 d_scanner_0_nonmem2rxRecords[3] = {
{d_shift_0_0_nonmem2rxRecords, {d_scanner_0_0_0_nonmem2rxRecords, d_scanner_0_0_1_nonmem2rxRecords
 , d_scanner_0_0_1_nonmem2rxRecords, d_scanner_0_0_1_nonmem2rxRecords}},
{d_shift_0_1_nonmem2rxRecords, {d_scanner_0_1_0_nonmem2rxRecords, d_scanner_0_0_1_nonmem2rxRecords
 , d_scanner_0_0_1_nonmem2rxRecords, d_scanner_0_0_1_nonmem2rxRecords}},
{d_shift_0_2_nonmem2rxRecords, {d_scanner_0_2_0_nonmem2rxRecords, d_scanner_0_0_1_nonmem2rxRecords
 , d_scanner_0_0_1_nonmem2rxRecords, d_scanner_0_0_1_nonmem2rxRecords}}
};

SB_trans_uint8 d_transition_0_nonmem2rxRecords[3] = {
{{d_accepts_diff_0_0_0_nonmem2rxRecords, d_accepts_diff_0_0_1_nonmem2rxRecords
 , d_accepts_diff_0_0_1_nonmem2rxRecords, d_accepts_diff_0_0_1_nonmem2rxRecords}},
{{d_accepts_diff_0_1_0_nonmem2rxRecords, d_accepts_diff_0_1_0_nonmem2rxRecords
 , d_accepts_diff_0_1_0_nonmem2rxRecords, d_accepts_diff_0_1_0_nonmem2rxRecords}},
{{d_accepts_diff_0_2_0_nonmem2rxRecords, d_accepts_diff_0_0_1_nonmem2rxRecords
 , d_accepts_diff_0_0_1_nonmem2rxRecords, d_accepts_diff_0_0_1_nonmem2rxRecords}}
};

SB_uint8 d_scanner_1_nonmem2rxRecords[2] = {
{NULL, {d_scanner_1_0_0_nonmem2rxRecords, d_scanner_1_0_1_nonmem2rxRecords
 , d_scanner_1_0_1_nonmem2rxRecords, d_scanner_1_0_1_nonmem2rxRecords}},
{d_shift_1_1_nonmem2rxRecords, {d_scanner_1_0_1_nonmem2rxRecords, d_scanner_1_0_1_nonmem2rxRecords
 , d_scanner_1_0_1_nonmem2rxRecords, d_scanner_1_0_1_nonmem2rxRecords}}
};

SB_trans_uint8 d_transition_1_nonmem2rxRecords[2] = {
{{d_accepts_diff_0_1_0_nonmem2rxRecords, d_accepts_diff_0_1_0_nonmem2rxRecords
 , d_accepts_diff_0_1_0_nonmem2rxRecords, d_accepts_diff_0_1_0_nonmem2rxRecords}},
{{d_accepts_diff_0_1_0_nonmem2rxRecords, d_accepts_diff_0_1_0_nonmem2rxRecords
 , d_accepts_diff_0_1_0_nonmem2rxRecords, d_accepts_diff_0_1_0_nonmem2rxRecords}}
};

SB_uint8 d_scanner_8_nonmem2rxRecords[2] = {
{NULL, {d_scanner_8_0_0_nonmem2rxRecords, d_scanner_1_0_1_nonmem2rxRecords
 , d_scanner_1_0_1_nonmem2rxRecords, d_scanner_1_0_1_nonmem2rxRecords}},
{d_shift_8_1_nonmem2rxRecords, {d_scanner_1_0_1_nonmem2rxRecords, d_scanner_1_0_1_nonmem2rxRecords
 , d_scanner_1_0_1_nonmem2rxRecords, d_scanner_1_0_1_nonmem2rxRecords}}
};

SB_trans_uint8 d_transition_8_nonmem2rxRecords[2] = {
{{d_accepts_diff_0_1_0_nonmem2rxRecords, d_accepts_diff_0_1_0_nonmem2rxRecords
 , d_accepts_diff_0_1_0_nonmem2rxRecords, d_accepts_diff_0_1_0_nonmem2rxRecords}},
{{d_accepts_diff_0_1_0_nonmem2rxRecords, d_accepts_diff_0_1_0_nonmem2rxRecords
 , d_accepts_diff_0_1_0_nonmem2rxRecords, d_accepts_diff_0_1_0_nonmem2rxRecords}}
};

SB_uint8 d_scanner_10_nonmem2rxRecords[2] = {
{d_shift_0_0_nonmem2rxRecords, {d_scanner_10_0_0_nonmem2rxRecords, d_scanner_1_0_1_nonmem2rxRecords
 , d_scanner_1_0_1_nonmem2rxRecords, d_scanner_1_0_1_nonmem2rxRecords}},
{d_shift_0_0_nonmem2rxRecords, {d_scanner_10_0_0_nonmem2rxRecords, d_scanner_1_0_1_nonmem2rxRecords
 , d_scanner_1_0_1_nonmem2rxRecords, d_scanner_1_0_1_nonmem2rxRecords}}
};

SB_trans_uint8 d_transition_10_nonmem2rxRecords[2] = {
{{d_accepts_diff_0_1_0_nonmem2rxRecords, d_accepts_diff_0_1_0_nonmem2rxRecords
 , d_accepts_diff_0_1_0_nonmem2rxRecords, d_accepts_diff_0_1_0_nonmem2rxRecords}},
{{d_accepts_diff_0_1_0_nonmem2rxRecords, d_accepts_diff_0_1_0_nonmem2rxRecords
 , d_accepts_diff_0_1_0_nonmem2rxRecords, d_accepts_diff_0_1_0_nonmem2rxRecords}}
};

SB_uint8 d_scanner_12_nonmem2rxRecords[2] = {
{d_shift_12_0_nonmem2rxRecords, {d_scanner_0_1_0_nonmem2rxRecords, d_scanner_0_0_1_nonmem2rxRecords
 , d_scanner_0_0_1_nonmem2rxRecords, d_scanner_0_0_1_nonmem2rxRecords}},
{d_shift_12_0_nonmem2rxRecords, {d_scanner_0_1_0_nonmem2rxRecords, d_scanner_0_0_1_nonmem2rxRecords
 , d_scanner_0_0_1_nonmem2rxRecords, d_scanner_0_0_1_nonmem2rxRecords}}
};

SB_trans_uint8 d_transition_12_nonmem2rxRecords[2] = {
{{d_accepts_diff_0_1_0_nonmem2rxRecords, d_accepts_diff_0_1_0_nonmem2rxRecords
 , d_accepts_diff_0_1_0_nonmem2rxRecords, d_accepts_diff_0_1_0_nonmem2rxRecords}},
{{d_accepts_diff_0_1_0_nonmem2rxRecords, d_accepts_diff_0_1_0_nonmem2rxRecords
 , d_accepts_diff_0_1_0_nonmem2rxRecords, d_accepts_diff_0_1_0_nonmem2rxRecords}}
};

SB_uint8 d_scanner_15_nonmem2rxRecords[2] = {
{NULL, {d_scanner_1_0_1_nonmem2rxRecords, d_scanner_15_0_1_nonmem2rxRecords
 , d_scanner_1_0_1_nonmem2rxRecords, d_scanner_1_0_1_nonmem2rxRecords}},
{d_shift_15_1_nonmem2rxRecords, {d_scanner_1_0_1_nonmem2rxRecords, d_scanner_15_0_1_nonmem2rxRecords
 , d_scanner_1_0_1_nonmem2rxRecords, d_scanner_1_0_1_nonmem2rxRecords}}
};

SB_trans_uint8 d_transition_15_nonmem2rxRecords[2] = {
{{d_accepts_diff_0_1_0_nonmem2rxRecords, d_accepts_diff_0_1_0_nonmem2rxRecords
 , d_accepts_diff_0_1_0_nonmem2rxRecords, d_accepts_diff_0_1_0_nonmem2rxRecords}},
{{d_accepts_diff_0_1_0_nonmem2rxRecords, d_accepts_diff_0_1_0_nonmem2rxRecords
 , d_accepts_diff_0_1_0_nonmem2rxRecords, d_accepts_diff_0_1_0_nonmem2rxRecords}}
};

SB_uint8 d_scanner_17_nonmem2rxRecords[2] = {
{d_shift_17_0_nonmem2rxRecords, {d_scanner_17_0_0_nonmem2rxRecords, d_scanner_0_0_1_nonmem2rxRecords
 , d_scanner_0_0_1_nonmem2rxRecords, d_scanner_0_0_1_nonmem2rxRecords}},
{d_shift_17_0_nonmem2rxRecords, {d_scanner_17_0_0_nonmem2rxRecords, d_scanner_0_0_1_nonmem2rxRecords
 , d_scanner_0_0_1_nonmem2rxRecords, d_scanner_0_0_1_nonmem2rxRecords}}
};

SB_trans_uint8 d_transition_17_nonmem2rxRecords[2] = {
{{d_accepts_diff_0_1_0_nonmem2rxRecords, d_accepts_diff_0_1_0_nonmem2rxRecords
 , d_accepts_diff_0_1_0_nonmem2rxRecords, d_accepts_diff_0_1_0_nonmem2rxRecords}},
{{d_accepts_diff_0_1_0_nonmem2rxRecords, d_accepts_diff_0_1_0_nonmem2rxRecords
 , d_accepts_diff_0_1_0_nonmem2rxRecords, d_accepts_diff_0_1_0_nonmem2rxRecords}}
};

unsigned char d_goto_valid_0_nonmem2rxRecords[] = {
0xbe,0x85,0x0};
unsigned char d_goto_valid_1_nonmem2rxRecords[] = {
0x0,0x8,0x0};
D_Reduction * d_reductions_2_nonmem2rxRecords[] = {&d_reduction_11_nonmem2rxRecords};
unsigned char d_goto_valid_4_nonmem2rxRecords[] = {
0xb8,0x85,0x0};
D_Reduction * d_reductions_4_nonmem2rxRecords[] = {&d_reduction_1_nonmem2rxRecords};
D_Reduction * d_reductions_5_nonmem2rxRecords[] = {&d_reduction_3_nonmem2rxRecords};
D_Reduction * d_reductions_6_nonmem2rxRecords[] = {&d_reduction_4_nonmem2rxRecords};
D_Reduction * d_reductions_7_nonmem2rxRecords[] = {&d_reduction_5_nonmem2rxRecords};
unsigned char d_goto_valid_8_nonmem2rxRecords[] = {
0x40,0x2,0x1};
D_Reduction * d_reductions_8_nonmem2rxRecords[] = {&d_reduction_9_nonmem2rxRecords};
D_RightEpsilonHint d_right_epsilon_hints_8_nonmem2rxRecords[] = {{0, 13, &d_reduction_7_nonmem2rxRecords}};
D_Reduction * d_reductions_9_nonmem2rxRecords[] = {&d_reduction_5_nonmem2rxRecords};
unsigned char d_goto_valid_10_nonmem2rxRecords[] = {
0x0,0x4,0x0};
D_Reduction * d_reductions_11_nonmem2rxRecords[] = {&d_reduction_2_nonmem2rxRecords};
unsigned char d_goto_valid_12_nonmem2rxRecords[] = {
0x0,0x0,0x2};
D_Reduction * d_reductions_13_nonmem2rxRecords[] = {&d_reduction_7_nonmem2rxRecords};
D_Reduction * d_reductions_14_nonmem2rxRecords[] = {&d_reduction_8_nonmem2rxRecords};
unsigned char d_goto_valid_15_nonmem2rxRecords[] = {
0x0,0x20,0x0};
D_Reduction * d_reductions_16_nonmem2rxRecords[] = {&d_reduction_12_nonmem2rxRecords};
unsigned char d_goto_valid_17_nonmem2rxRecords[] = {
0x0,0x40,0x0};
D_Reduction * d_reductions_18_nonmem2rxRecords[] = {&d_reduction_10_nonmem2rxRecords};
unsigned short d_gotos_nonmem2rxRecords[28] = {
4,5,6,7,8,11,9,10,16,2,17,12,7,8,3,9,
10,14,2,18,15,19,0,3,0,0,0,13};


D_State d_states_nonmem2rxRecords[] = {
{d_goto_valid_0_nonmem2rxRecords, 1, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_0_nonmem2rxRecords, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_0_nonmem2rxRecords, d_accepts_diff_0_nonmem2rxRecords, -1},
{d_goto_valid_1_nonmem2rxRecords, 6, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_1_nonmem2rxRecords, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_1_nonmem2rxRecords, d_accepts_diff_1_nonmem2rxRecords, -1},
{NULL, -2147483647, {1, d_reductions_2_nonmem2rxRecords}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {0, NULL}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 1, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_4_nonmem2rxRecords, -8, {1, d_reductions_4_nonmem2rxRecords}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_0_nonmem2rxRecords, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_0_nonmem2rxRecords, d_accepts_diff_0_nonmem2rxRecords, -1},
{NULL, -2147483647, {1, d_reductions_5_nonmem2rxRecords}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_6_nonmem2rxRecords}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_7_nonmem2rxRecords}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_8_nonmem2rxRecords, -11, {1, d_reductions_8_nonmem2rxRecords}, {1, d_right_epsilon_hints_8_nonmem2rxRecords}, {0, NULL}, 1, NULL, (void*)d_scanner_8_nonmem2rxRecords, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_8_nonmem2rxRecords, d_accepts_diff_8_nonmem2rxRecords, -1},
{NULL, -2147483647, {1, d_reductions_9_nonmem2rxRecords}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_10_nonmem2rxRecords, 2, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_10_nonmem2rxRecords, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_10_nonmem2rxRecords, d_accepts_diff_10_nonmem2rxRecords, -1},
{NULL, -2147483647, {1, d_reductions_11_nonmem2rxRecords}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_12_nonmem2rxRecords, 7, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_12_nonmem2rxRecords, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_12_nonmem2rxRecords, d_accepts_diff_12_nonmem2rxRecords, -1},
{NULL, -2147483647, {1, d_reductions_13_nonmem2rxRecords}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{NULL, -2147483647, {1, d_reductions_14_nonmem2rxRecords}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_15_nonmem2rxRecords, -6, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_15_nonmem2rxRecords, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_15_nonmem2rxRecords, d_accepts_diff_15_nonmem2rxRecords, -1},
{NULL, -2147483647, {1, d_reductions_16_nonmem2rxRecords}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1},
{d_goto_valid_17_nonmem2rxRecords, -7, {0, NULL}, {0, NULL}, {0, NULL}, 1, NULL, (void*)d_scanner_17_nonmem2rxRecords, sizeof(unsigned char) , 0, D_SCAN_ALL, (void*)d_transition_17_nonmem2rxRecords, d_accepts_diff_17_nonmem2rxRecords, -1},
{NULL, -2147483647, {1, d_reductions_18_nonmem2rxRecords}, {0, NULL}, {0, NULL}, 0, NULL, NULL, sizeof(unsigned char) , 0, D_SCAN_ALL, NULL, NULL, -1}
};

D_Symbol d_symbols_nonmem2rxRecords[] = {
{D_SYMBOL_EBNF, "0 Start", 7, -1},
{D_SYMBOL_NTERM, "statement_list", 14, -1},
{D_SYMBOL_INTERNAL, "statement_list__3", 17, -1},
{D_SYMBOL_EBNF, "statement_list__2", 17, -1},
{D_SYMBOL_NTERM, "statement", 9, -1},
{D_SYMBOL_NTERM, "recLine", 7, -1},
{D_SYMBOL_INTERNAL, "recLine__6", 10, -1},
{D_SYMBOL_NTERM, "singleLineRecord", 16, -1},
{D_SYMBOL_NTERM, "singleLineNoRecord", 18, -1},
{D_SYMBOL_NTERM, "singleLineComment", 17, -1},
{D_SYMBOL_REGEX, "[ \\t\\r]*", 10, -1},
{D_SYMBOL_REGEX, "[$]", 3, -1},
{D_SYMBOL_REGEX, "[ \\t\\r]*", 10, -1},
{D_SYMBOL_REGEX, "[A-Za-z]+", 9, -1},
{D_SYMBOL_REGEX, "[^\\n;$]*", 9, -1},
{D_SYMBOL_REGEX, "[^$][^\\n]*", 11, -1},
{D_SYMBOL_STRING, ";", 1, -1},
{D_SYMBOL_REGEX, "[^\\n]*", 7, -1},
};

D_ParserTables parser_tables_nonmem2rxRecords = {
19, d_states_nonmem2rxRecords, d_gotos_nonmem2rxRecords, 0, 18, d_symbols_nonmem2rxRecords, NULL, 0, NULL, 0};
